### PR TITLE
Davidl DCODAControlEvent

### PR DESCRIPTION
**Pull request by faustus123**
Add DCODAControlEvent objects which mainly carry unix timestamp info.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent

**Comment by faustus123** [comment]
Closing so I can re-submit with additional changes

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent

**Comment by faustus123** [comment]
Closing. Changes are now in another pull request.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/make_davidl_DCODAControlEvent.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_DCODAControlEvent/report_davidl_DCODAControlEvent.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_DCODAControlEvent

**Pull request closed without merging**
