### PR TITLE
Hdgeant memleak fixes rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/make_hdgeant_memleak_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/make_hdgeant_memleak_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/report_hdgeant_memleak_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/report_hdgeant_memleak_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj

**Comment by sparksn** [comment]
Looks like build failed due to network problems.
I tested it manually.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/make_hdgeant_memleak_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/make_hdgeant_memleak_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/report_hdgeant_memleak_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/report_hdgeant_memleak_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/make_hdgeant_memleak_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/make_hdgeant_memleak_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/report_hdgeant_memleak_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj/report_hdgeant_memleak_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_memleak_fixes_rtj

**Comment by sdobbs** [comment]
Please ignore the preceding comment - this was a test moving he builds off
of the late ifarm1102.

**Pull request merged**
