### PR TITLE
Update amorphous baseline with run 30808. This looks to have limited …

### PR DESCRIPTION
**Pull request by faustus123**
…stats since gluon47 died at some point in the run.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/make_davidl_monitoring.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/make_davidl_monitoring.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/report_davidl_monitoring.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/report_davidl_monitoring.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_monitoring

**Comment by sdobbs** [comment]
Hm, all the tests seem to have ended okay, but some failure codes were recorded?  @NathanSparks can you look at this?

**Comment by sparksn** [comment]
If you look in the log directory within the log directory(??), you will see
```
timeout: failed to run command 'hd_root': No such file or directory
```
It looks like the environment is not being set up properly for the tests.

**Comment by markito3** [comment]
I took over the /home/gluex/build_scripts directory for the hdgeant4 
build set-up. Could that be the problem?

**Comment by sparksn** [comment]
No, the tests are using /group/halld/Software/build_scripts.
This problem is related to the upgrade of the iFarm to CentOS 7.
The builds automatically switched over to gcc-4.8 compiler but the tests are still trying to use gcc-4.9.
I am working on a fix.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/make_davidl_monitoring.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/make_davidl_monitoring.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_monitoring/report_davidl_monitoring.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_monitoring/report_davidl_monitoring.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_monitoring

**Pull request merged**
