### PR TITLE
Reduce the size of the timewalk histograms

### PR DESCRIPTION
**Pull request by markdalton**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/make_dalton_BCAL_TDC_Timing.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/make_dalton_BCAL_TDC_Timing.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/report_dalton_BCAL_TDC_Timing.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/report_dalton_BCAL_TDC_Timing.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/make_dalton_BCAL_TDC_Timing.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/make_dalton_BCAL_TDC_Timing.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/report_dalton_BCAL_TDC_Timing.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/report_dalton_BCAL_TDC_Timing.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing

**Comment by sparksn** [comment]
Retrying the test... 
Ignore the previous failures. There was a technical issue.

**Comment by sparksn** [comment]
The last test attempt fizzled out for an unknown reason.
A build of this branch on my machine failed with:
```cpp
plugins/Calibration/BCAL_TDC_Timing/JEventProcessor_BCAL_TDC_Timing.cc:241:36: error: ‘NBINS_TDIFF’ was not declared in this scope
                   576, 0.5, 576.5, NBINS_TDIFF, MIN_TDIFF, MAX_TDIFF);
```
Apparently, declaration of `NBINS_TDIFF` was accidentally deleted.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/make_dalton_BCAL_TDC_Timing.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/make_dalton_BCAL_TDC_Timing.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/report_dalton_BCAL_TDC_Timing.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing/report_dalton_BCAL_TDC_Timing.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_BCAL_TDC_Timing

**Pull request closed without merging**
