### PR TITLE
Sqlitecpp standalone

### PR DESCRIPTION
**Pull request by markito3**
Uses the new SQLiteCpp library to support RCDB reading of SQLite files. Changes needed to SBMS and mcsmear to use the new scheme.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlitecpp_standalone/make_sqlitecpp_standalone.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlitecpp_standalone/make_sqlitecpp_standalone.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlitecpp_standalone/report_sqlitecpp_standalone.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlitecpp_standalone/report_sqlitecpp_standalone.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlitecpp_standalone

**Comment by markito3** [comment]
Needed to change the test build environment at JLab back to using the default versions. Made the change and re-submitted the test build.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sqlitecpp_standalone/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlitecpp_standalone/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sqlitecpp_standalone/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlitecpp_standalone/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlitecpp_standalone/make_sqlitecpp_standalone.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlitecpp_standalone/make_sqlitecpp_standalone.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlitecpp_standalone/report_sqlitecpp_standalone.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlitecpp_standalone/report_sqlitecpp_standalone.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlitecpp_standalone

**Comment by markito3** [comment]
Thanks for the merge Simon. You are a brave man. ;-)

**Pull request merged**
