### PR TITLE
Add plugin for filling a TPOL analysis tree

### PR DESCRIPTION
**Pull request by sparksn**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^ns_TPOL_tree/make_ns_TPOL_tree.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TPOL_tree/make_ns_TPOL_tree.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_TPOL_tree/report_ns_TPOL_tree.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TPOL_tree/report_ns_TPOL_tree.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_TPOL_tree

**Comment by markito3** [comment]
could have something to do with slash in branch name?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^ns_TPOL_tree/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TPOL_tree/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ns_TPOL_tree/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TPOL_tree/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^ns_TPOL_tree/make_ns_TPOL_tree.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TPOL_tree/make_ns_TPOL_tree.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_TPOL_tree/report_ns_TPOL_tree.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TPOL_tree/report_ns_TPOL_tree.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_TPOL_tree

**Comment by sparksn** [comment]
The initial build failure was not related to the slash in the branch name, or any problems with the code.
I updated this branch after opening the pull request, which apparently triggered the failure.

**Pull request merged**
