### PR TITLE
Use run number to get/update existing constants.

### PR DESCRIPTION
**Pull request by pmattjlab**
Ditto.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^rf_calibrun/make_rf_calibrun.log](https://halldweb.jlab.org/pull_request_test/sim-recon^rf_calibrun/make_rf_calibrun.log)
 Build report: [/work/halld/pull_request_test/sim-recon^rf_calibrun/report_rf_calibrun.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^rf_calibrun/report_rf_calibrun.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^rf_calibrun

**Comment by pmattjlab** [comment]
Well that's odd.  I only changed files that aren't even compiled.

**Comment by sdobbs** [comment]
It looks like it's an error introduced by @faustus123 on Oct. 9 - I don't see a corresponding pull request for the change to HDEVIO.cc, so maybe it was pushed directly to the branch?

**Comment by faustus123** [comment]
This was a change I pushed to a branch that is currently being tested (bufferd_hdevio). I didn’t think it should
show up on the master branch yet. Did it somehow seep in there?

**Comment by sdobbs** [comment]
Yeah, it looks like it got onto the master somehow.

**Comment by sparksn** [comment]
According to the "Public activity" in his profile, it looks like @faustus123 accidentally pushed to master some time this morning.

**Comment by faustus123** [comment]
OK, I think know what happened. I was working locally on “master” and pushed
the HDEVIO changes to a new branch on Github, but then started working on
some different changes also locally on master, and pushed those to another
new branch that had the pull request this morning. 

My Bad.

**Comment by sdobbs** [comment]
Sounds good.  I guess this means that the system is working?  :smiley:

**Pull request merged**
