### PR TITLE
Search the custom sqlite directory for libraries at link time as well as at run time.

### PR DESCRIPTION
**Pull request by markito3**
Problem was discovered when trying a build where sqlite was not installed via RPM.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlite_link_fix

**Comment by markito3** [comment]
This needs a new build_scripts to work (I realize now). The one on the CUE now is too old. The sqlite library also needs to be rebuilt with the new version. Let's let this one sit for now until the build_scripts update goes through.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlite_link_fix

**Comment by markito3** [comment]
OK. Trying again...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlite_link_fix

**Comment by markito3** [comment]
One more time...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlite_link_fix

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlite_link_fix

**Comment by markito3** [comment]
I got this...really...  ;-)

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/make_sqlite_link_fix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sqlite_link_fix/report_sqlite_link_fix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sqlite_link_fix

**Comment by markito3** [comment]
...bump...

**Pull request merged**
