### PR TITLE
Monitoring plugin changes

### PR DESCRIPTION
**Pull request by sdobbs**
- Remake ppi0gamma_hists so that it makes similar output to p3pi_hists
  [cuts probably need to be tweaked]
- Add some basic monitoring of F1TDC error conditions to lowlevel_online

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^sdobbs_monitoring_mods/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_monitoring_mods/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_monitoring_mods/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_monitoring_mods/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_monitoring_mods/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_monitoring_mods/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_monitoring_mods/make_sdobbs_monitoring_mods.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_monitoring_mods/make_sdobbs_monitoring_mods.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_monitoring_mods/report_sdobbs_monitoring_mods.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_monitoring_mods/report_sdobbs_monitoring_mods.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_monitoring_mods

**Comment by markito3** [comment]
I am confused. Should I be worried? How do we assess the nature of the hdgeant failure?

**Comment by sdobbs** [comment]
It was due to another timeout. We should either increase the timeout window
or look into the root cause of these more deeply since they seem to be
happening more lately.

**Comment by sparksn** [comment]
No, the log shows an actual error here. The cause is unclear though (disk issues?).
Increasing the timeout window will not help.

By the way, I checked and there was an actual bug that was causing the PR #778 tests to timeout.
It only presents itself when processing a subsample of events in a file.
@faustus123 is looking into it.

**Pull request merged**
