### PR TITLE
More timing monitoring updates, also new calibration code

### PR DESCRIPTION
**Pull request by sdobbs**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/make_sdobbs_hldt2018_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/make_sdobbs_hldt2018_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/report_sdobbs_hldt2018_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/report_sdobbs_hldt2018_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates

**Comment by sdobbs** [comment]
Note that the tests are failing since  /work/halld/pull_request_test/hd_rawdata_030858_8k.evio is missing...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/make_sdobbs_hldt2018_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/make_sdobbs_hldt2018_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates/report_sdobbs_hldt2018_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt2018_updates/report_sdobbs_hldt2018_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_hldt2018_updates

**Comment by markito3** [comment]
The fix I put in got lost messing with the version of build_scripts in the production area. It is back in there now.

**Pull request merged**
