### PR TITLE
Exclusive pi0 skim update

### PR DESCRIPTION
**Pull request by sdobbs**
- update plugin for new analysis library
- only write out the showers and vertex information, since that's what is needed for the calibration
  note that we write out one "event" per combo... but having multiple combos that pass the kinematic fitter in this case should be pretty rare

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/make_sdobbs_excl_pi0_plugin.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/make_sdobbs_excl_pi0_plugin.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/report_sdobbs_excl_pi0_plugin.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/report_sdobbs_excl_pi0_plugin.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin

**Comment by pmattjlab** [comment]
This plugin is just as broken as the omega_skim plugin was.  See the comments on that pull request and please fix it.

**Comment by sdobbs** [comment]
Is the problem the pi0 constraint business?

**Comment by aaust** [comment]
No, it is the line where you check the analysisResultsVector[0]. This probes the first reaction in line, which is not necessarily yours.

**Comment by sdobbs** [comment]
Thanks for the reminder, I was trying to remember which PR fixed the problem...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/make_sdobbs_excl_pi0_plugin.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/make_sdobbs_excl_pi0_plugin.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/report_sdobbs_excl_pi0_plugin.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/report_sdobbs_excl_pi0_plugin.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin

**Comment by sdobbs** [comment]
One test got interrupted, there is currently one running

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/make_sdobbs_excl_pi0_plugin.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/make_sdobbs_excl_pi0_plugin.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/report_sdobbs_excl_pi0_plugin.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin/report_sdobbs_excl_pi0_plugin.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_excl_pi0_plugin

**Pull request merged**
