### PR TITLE
Neutral shower covariance matrix

### PR DESCRIPTION
**Pull request by markdalton**
This series of commits has been tested by Paul and found to work, and in general provide an improvement in the results of the kinematic fit.  It is therefore ready to go.  I have a few tweaks to make, which I will do from the master.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance/make_dalton_BCAL_covariance.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_covariance/make_dalton_BCAL_covariance.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance/report_dalton_BCAL_covariance.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_covariance/report_dalton_BCAL_covariance.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance

**Comment by sdobbs** [comment]
Restarting build...

**Comment by gluex** [comment]
Test status for this pull request: FAILURE

 Failures: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_covariance/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_covariance/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_covariance/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance/make_dalton_BCAL_covariance.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_covariance/make_dalton_BCAL_covariance.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance/report_dalton_BCAL_covariance.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_BCAL_covariance/report_dalton_BCAL_covariance.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_BCAL_covariance

**Comment by sdobbs** [comment]
Just runtime errors on the tests, so am merging.

Will work on bringing the production build_scripts back to the master...

**Pull request merged**
