### PR TITLE
Ps new

### PR DESCRIPTION
**Pull request by somovalex**
Some modifications in the simulation and reconstruction of the PS/PSC

### CODE REVIEW

**Comment by sdobbs** [comment]
A question for the experts:  do we want to allow "new" calls in a class definition?  This feels like asking for trouble to me, but I didn't even know you could do that in C++11 =)

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^ps_new/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ps_new/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^ps_new/make_ps_new.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/make_ps_new.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ps_new/report_ps_new.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/report_ps_new.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ps_new

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^ps_new/make_ps_new.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/make_ps_new.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ps_new/report_ps_new.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/report_ps_new.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ps_new

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^ps_new/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ps_new/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^ps_new/make_ps_new.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/make_ps_new.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ps_new/report_ps_new.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_new/report_ps_new.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ps_new

**Comment by sdobbs** [comment]
Merging now that the previous comment doesn't apply anymore, but worth discussing in any case...

**Pull request merged**
