### PR TITLE
make sure DCDCDigiHit can handle FDC type readout mode

### PR DESCRIPTION
**Pull request by zihlmann**
modified the DCDCHit fatory to handle CDC data taken with FDC readout mode

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^cdchithandleFDCreadout/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^cdchithandleFDCreadout/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^cdchithandleFDCreadout/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^cdchithandleFDCreadout/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^cdchithandleFDCreadout/make_cdchithandleFDCreadout.log](https://halldweb.jlab.org/pull_request_test/sim-recon^cdchithandleFDCreadout/make_cdchithandleFDCreadout.log)
 Build report: [/work/halld/pull_request_test/sim-recon^cdchithandleFDCreadout/report_cdchithandleFDCreadout.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^cdchithandleFDCreadout/report_cdchithandleFDCreadout.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^cdchithandleFDCreadout

**Comment by nsjarvis** [comment]
While we're looking at this, why is raw_amp in the hit object (where it's a float) and why isn't the pedestal subtracted from it?

**Comment by nsjarvis** [comment]
Beni did you test this in long mode?  I think it will find the emulated CDCPulse.

**Review by sdobbs — APPROVED** [review]
My cat seems skeptical, but this looks okay to me, now that the pulse peak is being filled in the translation table stage correctly.

**Comment by nsjarvis** [comment]
Er, what?  I think that with long mode data, the code will find the window
raw data associated with the cdc roc ids and then go ahead and emulate the
cdcpulse which is missing.  Digihits will then end up using the emulated
pulse height instead of the real one which is in the fdcpulse.  :-(


What about raw_amp and the pedestal, should the pedestal be subtracted from
raw_amp?  Also raw_amp is changing type undercover several times on its way
into the HDDM (or wherever it was) code which seems rather dodgy.

**Comment by sdobbs** [comment]
Ah, I misinterpreted your request.  I'm not sure that what you are saying will happen, but I agree that the logic needs to be cleaned up. I'll take care of that...

**Pull request merged**
