### PR TITLE
correct blocks of code that get turned on when there is GPU acceleration

### PR DESCRIPTION
**Pull request by mashephe**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/make_fix_GPU_comment.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/make_fix_GPU_comment.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/report_fix_GPU_comment.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/report_fix_GPU_comment.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fix_GPU_comment

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/make_fix_GPU_comment.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/make_fix_GPU_comment.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/report_fix_GPU_comment.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/report_fix_GPU_comment.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fix_GPU_comment

**Comment by sdobbs** [comment]
Please ignore any more messages on this issue, testing a new feature...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/make_fix_GPU_comment.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/make_fix_GPU_comment.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fix_GPU_comment/report_fix_GPU_comment.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_GPU_comment/report_fix_GPU_comment.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fix_GPU_comment

**Pull request merged**
