### PR TITLE
add comment about deprecation of make

### PR DESCRIPTION
**Pull request by markito3**
try the test again

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^test-pr/make_test-pr.log](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/make_test-pr.log)
 Build report: [/work/halld/pull_request_test/sim-recon^test-pr/report_test-pr.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/report_test-pr.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^test-pr

**Comment by markito3** [comment]
and again

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^test-pr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^test-pr/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^test-pr/make_test-pr.log](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/make_test-pr.log)
 Build report: [/work/halld/pull_request_test/sim-recon^test-pr/report_test-pr.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/report_test-pr.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^test-pr

**Comment by markito3** [comment]
Note that pull requests are not being built against JANA 0.7.5p1. This is not the case for the "standard" configuration. That will change in the near future however.

**Comment by markito3** [comment]
Colleagues,

In my opinion, it would be safe to merge this pull request.

  -- Mark

**Comment by sparksn** [comment]
I don't know about that. Looks kind of suspicious to me.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^test-pr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^test-pr/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^test-pr/make_test-pr.log](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/make_test-pr.log)
 Build report: [/work/halld/pull_request_test/sim-recon^test-pr/report_test-pr.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test-pr/report_test-pr.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^test-pr

**Pull request merged**
