### PR TITLE
added PREFIX scons option to outsource build

### PR DESCRIPTION
**Pull request by werthm**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^build_prefix/make_build_prefix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^build_prefix/make_build_prefix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^build_prefix/report_build_prefix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^build_prefix/report_build_prefix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^build_prefix

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^build_prefix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^build_prefix/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^build_prefix/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^build_prefix/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^build_prefix/make_build_prefix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^build_prefix/make_build_prefix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^build_prefix/report_build_prefix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^build_prefix/report_build_prefix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^build_prefix

**Comment by faustus123** [comment]
Hi Dominik,

 I’m just now trying to catch up on a few things. I tried looking at the build log for this, but it
is unclear if the link it points i is still relevant for the build of your branch. Do you know
what the issue was that caused the build to fail?

Regards,
-David

**Comment by sparksn** [comment]
The build failed because the pull request was initiated on a branch from @werthm's  "namespace", not JeffersonLab. The build script assumes the branch has been pushed to JeffersonLab.

Privately, I told Dominik that I think the addition of a PREFIX is a good idea, but I would like to see it support `scons -c`, which did not work for me when I tested this branch.

**Comment by sparksn** [comment]
I have to retract my explanation for why the test failed.
I just tested this with my own fork/PR #244, and the build and tests passed.
Actually, the tests were applied to the master branch of JeffersonLab/sim-recon (see the build log),
so the tests are currently meaningless if they are initiated by a PR from a forked repo.

I am not sure why that first test failed at the build stage, but I remember looking at the log and seeing
that it never actually started building; I assumed this occurred because the PR came from a fork.
Anyway, I tested this branch by hand and it was successful.

**Comment by werthm** [comment]
Hi guys

I'm currently traveling back to Glasgow so I cannot do any tests at the moment. I cancelled my pull request and deleted my fork since I joined the JLab team on github now and will commit to my own branch in the main repo in the future. I already got an idea to make scons -c work and will make a pull request once it's ready.

Cheers,
Dominik

**Comment by markito3** [comment]
I understand that Dominik intends to commit to the main repo, but we should look at the script and see if we can accommodate the pull request coming from a private account. I'll bet we can. We would need the repo info as well as the branch and the JLab-side script never gets that info at present; the main repo is hard-wired.

I think we will continue to require pull requests coming from GitHub however.

**Comment by sdobbs** [comment]
Yes, we can add the repo information to the PR scripts - it probably makes sense to pass along the URL of the repo.

I don't think that PRs can come from a non-GitHub source?

**Comment by markito3** [comment]
@sdobbs is right. We are using the GitHub pull request mechanism, so pull requests must come from GitHub to trigger the auto-build-and-test. I was thinking that one could imagine an even more general system that accomodates non-github pull requests, but that is a much higher bar. First we would have to define standards for a non-github pull request, then we would have to...so I was ruling that out. (Perhaps commercial systems would work, but I do not know about that.)

**Comment by sdobbs** [comment]
The test builds should work now for forked repos as well.  @NathanSparks and @werthm, could you please test this some more?

**Pull request closed without merging**
