### PR TITLE
TAC hits 

### PR DESCRIPTION
**Pull request by hovanes-egiyan**
Added a sim-recon library to generate TAC hits for PS normalization/calibration runs for online monitoring.

### CODE REVIEW

**Comment by sdobbs** [comment]
Let me kick off the automated test for this branch...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log)
 Build report: [/work/halld/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^tac_hits-0

**Comment by sdobbs** [comment]
I see - this PR is created from Hovanes' fork of this repo.  I forget if we decided to support this case.  Let me take a look...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log)
 Build report: [/work/halld/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^tac_hits-0

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log)
 Build report: [/work/halld/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^tac_hits-0

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log)
 Build report: [/work/halld/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^tac_hits-0

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/make_tac_hits-0.log)
 Build report: [/work/halld/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^tac_hits-0/report_tac_hits-0.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^tac_hits-0

**Comment by sdobbs** [comment]
OK, needed to make a couple bug fixes.

As a reminder, we don't run the automated tests on forked repos due to security concerns.  So I'll merge these changes and watch the nightly build to confirm that we still build properly.

**Comment by hovanes-egiyan** [comment]
Thanks for checking and merging it.I probably will use a branch on the mainGluex repository instead of forking next time. Hovanes


Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Pull request merged**
