### PR TITLE
First stage of Geometry Updates

### PR DESCRIPTION
**Pull request by sdobbs**
First pass at rewriting geometry code to better factorize it and to add in more alignment constants. Generally, put all the XML handling code in DGeometry, and centralize more of the calculations in there as well.  Local detector classes are responsible for transforming the geometry into what is needed by the reconstruction algorithms.

TOF geometry generalization should help in the future as well.

Still a few more changes to make, but adding what I have now before the sim-recon split.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_geom_updates

**Comment by sdobbs** [comment]
I hope someone merges me before sim-recon is locked! 😄

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_geom_updates

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_geom_updates

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/make_sdobbs_geom_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_geom_updates/report_sdobbs_geom_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_geom_updates

**Pull request merged**
