### PR TITLE
Minor timing plugin update

### PR DESCRIPTION
**Pull request by sdobbs**
Remove redundant namespace specifier in one HLDetectorTiming script that crashes ROOT 6. 
This one is probably my fault..

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt_update/make_sdobbs_hldt_update.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt_update/make_sdobbs_hldt_update.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt_update/report_sdobbs_hldt_update.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt_update/report_sdobbs_hldt_update.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_hldt_update

**Comment by sdobbs** [comment]
I bet this is a similar problem with the JLab certificate needing to be installed.
Investigating...

**Comment by sdobbs** [comment]
Yup, that was it - test build in progress...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt_update/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt_update/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt_update/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt_update/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt_update/make_sdobbs_hldt_update.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt_update/make_sdobbs_hldt_update.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_hldt_update/report_sdobbs_hldt_update.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_hldt_update/report_sdobbs_hldt_update.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_hldt_update

**Pull request merged**
