### PR TITLE
Various mcsmear changes

### PR DESCRIPTION
**Pull request by sdobbs**
Merge changes from the 2017 mcsmear branch into the main trunk.  Includes:
- Changes to HDDM format to store pulse peak information
- Using per-channel thresholds for CDC smearing
- FDC cathode plane swap fix

### CODE REVIEW

**Comment by sdobbs** [comment]
PS: Don't delete this branch after merging!

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/make_recon-2017_01-ver01-batch01-mcsmear-mergemaster.log](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/make_recon-2017_01-ver01-batch01-mcsmear-mergemaster.log)
 Build report: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/report_recon-2017_01-ver01-batch01-mcsmear-mergemaster.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/report_recon-2017_01-ver01-batch01-mcsmear-mergemaster.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/make_recon-2017_01-ver01-batch01-mcsmear-mergemaster.log](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/make_recon-2017_01-ver01-batch01-mcsmear-mergemaster.log)
 Build report: [/work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/report_recon-2017_01-ver01-batch01-mcsmear-mergemaster.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster/report_recon-2017_01-ver01-batch01-mcsmear-mergemaster.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^recon-2017_01-ver01-batch01-mcsmear-mergemaster

**Comment by sdobbs** [comment]
Thanks =)

**Pull request merged**
