### PR TITLE
Davidl c++11

### PR DESCRIPTION
**Pull request by faustus123**
Make C++11 a requirement.

This also implements some small tracking fixes (presented at last Offline meeting) and the new parser, though the old parser is set as the default.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_c++11

**Comment by zisis0** [comment]
Wow!  This list probably wins the World Cup championship of github check-ins!  A lot of work, man.

By the way, I had a chat with my IT guy yesterday.  He was ready to bring argus down to upgrade to Drupal 8, but because argus' Debian needs upgrading too I stopped him, cause I did not want any issues with DocDB’s accessibility by the collaboration.  I explained what is going on with the JDocDB stuff and put him on a holding pattern until we hear from Sherman.

Cheers, Zisis...

> On Jun 1, 2016, at 8:55 AM, David Lawrence notifications@github.com wrote:
> 
> Make C++11 a requirement.
> 
> This also implements some small tracking fixes (presented at last Offline meeting) and the new parser, though the old parser is set as the default.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/JeffersonLab/sim-recon/pull/406 https://github.com/JeffersonLab/sim-recon/pull/406
> Commit Summary
> 
> Added hdfast_parse utility used only for developing a faster EVIO event source. Some modifications to HDEVIO were made to support this.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Compile everything with -std=c++11. Added JEventSource_EVIOpp and changed hdfast_parse to use it.
> Protect against multiple includes
> Fixed bug in reading EVIO blocks with multiple events. Implemented vectors for all data types in DParsedEvent. Create DEPICSvalue objects from EPICS events.
> Continued developement of JEventSource_EVIOpp. Fixed some bugs. Creates Df250 objects (except WindowRawData) but does not make associations.
> Added parseing of F1TDC data. Fixed bug where only first module of fADC data was being parsed.
> Add creaton of DCAEN1290TDCHit objects
> Implemented use of translation table. Optimized (or at least attempted to) application of translation table.
> include string.h so memcpy is available
> Fix sync event header identification. bug
> Set the evnt_called flag for all factories.
> Implementing linking of associations. Saving work so I can switch back to master for some work there.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Merge branch 'davidl_c++11' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Can't send stringstream into stream operator. Need to access underlying string object.
> Fixed linking of associated TrigTime objects. Added SWAP, LINK, and various PARSE_XXX flags for controlling features from command line.
> Implemented pools for data objects. Some work done on linking. Race condition bug still seems to exist since parsing gets thron off.
> Throw exception rather than just return 0 when encountering an error in swap_bank. This makes things cleaner in DEVIOWorkerThread::Run.
> Fixed some issues with linking triggerTime and pulse objects.
> Fixed linking associated objects (not all links complete yet!) Added ability to read from ET.
> If exception caught in in worker thread, don't exit, but instead delete all objects and continue to next event. Also, identify and ignore 0xE10 bank data which looks to be another type introduced in the ROL via conf_utils.c
> Merged in master.
> Remove TLS_PARSED_EVENT global which seemed unneccessary. Move BOR data types to separate list so they can be owned outside of DParsedEvents. Implement Pruning of DParsedEvent objects as well as hit object pools to reduce average memory use.
> Commented out several object associations that appear to be unused according to survey.
> Implement BOR events and set event status bits. Adding BORConfig objects as associated objects is not yet implemented.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Finish implementation of BORConfig objects including linking as associated objects.
> Add linking of window raw data (though those objects are not yet created by parser). Updated some comments.
> Minor tweaks to suppress compiler warnings on Linux gcc4.9.2
> Fixed bug with multiple applications of translation table. Added EVIO:RUN_NUMBNER (USER_RUN_NUMBER).
> Increase max events before pruning to 1000 for both DParsedEvents and hit objects. Moved clearing of hit object vectors into sepearate macro.
> Attempt to fix bug in original parser where laste several events from file are dropped.
> Merge branch 'davidl_c++11' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Partially fixed bugs in reading all events with old parser. (Now it reads too many ??!)
> Fixed bug in old parser that caused it to read too many events.
> Add parsing of Built Trigger Bank to produce DCODAROCInfo and DCODAEventInfo objects. Temporarily disable sorting of hit objects while tracking down another bug.
> Added SearchFileForRunNumber method (which is a copy of the EpicQuestForRunNumber method of JEventSource_EVIO.) This is called from constructor to get an initial run number when reading from a file so calibrations and field maps are read in correctly on the first event.
> Added association method with ped copy. This may be temporary.
> Add link routine to copy integral samples from f250 PI. This is temporary.
> Refactored linking routines to use lambda functions.
> Add l3bdt plugin for training/testing BDT that could be used in L3 trigger.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Moved complex linking routines and sorting routines to commented out section at bottom of file. It looks like they don't really buy that much (if anything) in speed after all.
> Added production of window raw data objects and emulation of f250 (emulation of f125 not yet implemented.)
> Enable emulation of f125.
> Add MAX_EVENT_RECYCLES and MAX_OBJECT_RECYCLES. Reinstated sorting and complex linking to test rates since BOR linking slows things down.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Moved sorting and linking routines into LinkAssociations.h. Renamed 'LinkAssociationXXX' to more appropriate 'MatchXXX'. Moved matching/linking of BOR objects to use routines in LinkAssociations.h
> Add C++11 support to SConstruct.plugin
> Move call of DEVIOWorkerThread::Prune to MakeEvents so that DParsedEvents are not being pruned by one thread while another is trying to use them. Also, temporarily preserve order of hit objects and use slower link methods while debugging.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Comment out code that preserves sorting of hit objects. It is now clear that the sorting only enhanced the effect of the race condition that actually caused the apparent discrepancy between the new and old parsers.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Allow recording of call stack for janadot.
> Comment out getting of DF1TDCHit objects which are never used in DSCHit_factory
> Some changes to make tracking results independent of order of objects
> Remove commented out code that restored original order of hit objects. This is no longer needed since the issue was has been chased downstream.
> Fix an apparently a long standing bug (10 years?) where the charge of the last strip in a DFDCCathodeCluster was not added to q_tot.
> Move sorting of FDC wire hits downstream to DFDCPseudo where it is needed.
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Merge branch 'master' of https://github.com/JeffersonLab/sim-recon into davidl_c++11
> Change values returned by new parser so that it makes the old parser the default.
> Protect use of variable that only exist when ET support is compiled in with preprocessor directives.
> File Changes
> 
> M src/SBMS/SConstruct.plugin https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-0 (5)
> M src/SConstruct https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-1 (3)
> M src/libraries/DANA/DApplication.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-2 (2)
> A src/libraries/DAQ/DBORptrs.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-3 (69)
> M src/libraries/DAQ/DCAEN1290TDCConfig.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-4 (1)
> A src/libraries/DAQ/DEVIOWorkerThread.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-5 (1842)
> A src/libraries/DAQ/DEVIOWorkerThread.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-6 (154)
> M src/libraries/DAQ/DF1TDCConfig.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-7 (1)
> A src/libraries/DAQ/DParsedEvent.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-8 (295)
> M src/libraries/DAQ/Df125Config.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-9 (4)
> M src/libraries/DAQ/Df250Config.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-10 (1)
> M src/libraries/DAQ/Df250EmulatorAlgorithm.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-11 (18)
> M src/libraries/DAQ/Df250EmulatorAlgorithm_v1.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-12 (6)
> M src/libraries/DAQ/Df250EmulatorAlgorithm_v1.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-13 (9)
> A src/libraries/DAQ/HDET.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-14 (409)
> A src/libraries/DAQ/HDET.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-15 (79)
> A src/libraries/DAQ/JEventSourceGenerator_EVIOpp.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-16 (61)
> A src/libraries/DAQ/JEventSourceGenerator_EVIOpp.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-17 (31)
> M src/libraries/DAQ/JEventSource_EVIO.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-18 (74)
> M src/libraries/DAQ/JEventSource_EVIO.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-19 (2)
> A src/libraries/DAQ/JEventSource_EVIOpp.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-20 (881)
> A src/libraries/DAQ/JEventSource_EVIOpp.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-21 (201)
> A src/libraries/DAQ/LinkAssociations.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-22 (472)
> M src/libraries/DAQ/daq_param_type.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-23 (5)
> A src/libraries/DAQ/swap_bank.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-24 (194)
> A src/libraries/DAQ/swap_bank.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-25 (71)
> M src/libraries/FDC/DFDCCathodeCluster_factory.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-26 (85)
> M src/libraries/FDC/DFDCPseudo_factory.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-27 (5)
> M src/libraries/START_COUNTER/DSCHit_factory.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-28 (4)
> M src/libraries/TRACKING/DTrackHitSelectorALT2.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-29 (24)
> M src/libraries/TTAB/DTranslationTable.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-30 (394)
> M src/libraries/TTAB/DTranslationTable.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-31 (102)
> M src/plugins/Utilities/SConscript https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-32 (2)
> A src/plugins/Utilities/l3bdt/JEventProcessor_L3BDTtree.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-33 (193)
> A src/plugins/Utilities/l3bdt/JEventProcessor_L3BDTtree.h https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-34 (50)
> A src/plugins/Utilities/l3bdt/README https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-35 (25)
> A src/plugins/Utilities/l3bdt/SConscript https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-36 (13)
> A src/plugins/Utilities/l3bdt/trainBDT.C https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-37 (60)
> M src/programs/Utilities/SConscript https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-38 (2)
> M src/programs/Utilities/hddm/hddm-xml.cpp https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-39 (2)
> M src/programs/Utilities/hddm/xml-hddm.cpp https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-40 (2)
> A src/programs/Utilities/hdfast_parse/SConscript https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-41 (17)
> A src/programs/Utilities/hdfast_parse/hdfast_parse.cc https://github.com/JeffersonLab/sim-recon/pull/406/files#diff-42 (207)
> Patch Links:
> 
> https://github.com/JeffersonLab/sim-recon/pull/406.patch https://github.com/JeffersonLab/sim-recon/pull/406.patch
> https://github.com/JeffersonLab/sim-recon/pull/406.diff https://github.com/JeffersonLab/sim-recon/pull/406.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub https://github.com/JeffersonLab/sim-recon/pull/406, or mute the thread https://github.com/notifications/unsubscribe/AMDSOn3ltyO8VncUHYbpNA3v1xX41eNAks5qHZ1MgaJpZM4IroxQ.

Dr. Zisis Papandreou

## Professor of Physics, Ph.D., P.Phys.

Department of Physics  
University of Regina  
3737 Wascana Parkway
Regina, SK  S4S 0A2  CANADA

Phone: (306) 585-5379
Fax: (306) 585-5659
Email:  zisis@uregina.ca mailto:zisis@uregina.ca
Website: http://www.uregina.ca/science/physics/people/faculty-research/zisis-papandreou/index.html http://www.uregina.ca/science/physics/people/faculty-research/zisis-papandreou/index.html

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_c++11

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_c++11

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_c++11

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_c++11

**Comment by sdobbs** [comment]
Build is going forward now - sorry for the failure spam!

**Comment by gluex** [comment]
Test status for this pull request: FAILURE

 Failures: [/work/halld/pull_request_test/sim-recon^davidl_c++11/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/tests/failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^davidl_c++11/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_c++11/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_c++11

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^davidl_c++11/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_c++11/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/make_davidl_c++11.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_c++11/report_davidl_c++11.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_c++11

**Pull request merged**
