### PR TITLE
prevent a crash in TAGM_online if nsamples_pedestal is 0

### PR DESCRIPTION
**Pull request by aaust**
default error message provided by JANA

### CODE REVIEW

**Comment by sdobbs** [comment]
Yikes, do we have data with this condition?  Which run?

**Comment by aaust** [comment]
a few, e.g. 040348

**Comment by sdobbs** [comment]
Thanks, I hope this is due to the non-standard DAQ...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^aaust_TAGM_online_div0/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_TAGM_online_div0/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^aaust_TAGM_online_div0/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_TAGM_online_div0/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^aaust_TAGM_online_div0/make_aaust_TAGM_online_div0.log](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_TAGM_online_div0/make_aaust_TAGM_online_div0.log)
 Build report: [/work/halld/pull_request_test/sim-recon^aaust_TAGM_online_div0/report_aaust_TAGM_online_div0.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_TAGM_online_div0/report_aaust_TAGM_online_div0.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^aaust_TAGM_online_div0

**Pull request merged**
