### PR TITLE
Omega SDMEs

### PR DESCRIPTION
**Pull request by mikestaib**
Some code from my thesis work. Could use a little cleaning, but merging to prepare for centralization of some components of the simulation.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/make_OmegaSDMEs.log](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/make_OmegaSDMEs.log)
 Build report: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/report_OmegaSDMEs.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/report_OmegaSDMEs.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^OmegaSDMEs

**Comment by mikestaib** [comment]
Ah dang it, code requires new version of AmpTools, to make pretty plots with the background separated from the reweighed MC. But I think that code is still on a branch @mashephe ?

[Bin1CosTheta.pdf](https://github.com/JeffersonLab/sim-recon/files/1427567/Bin1CosTheta.pdf)
[Bin1phi-1.pdf](https://github.com/JeffersonLab/sim-recon/files/1427568/Bin1phi-1.pdf)
[Bin1Phi.pdf](https://github.com/JeffersonLab/sim-recon/files/1427569/Bin1Phi.pdf)

**Comment by mashephe** [comment]
Mike,

I just made v0.9.3 of AmpTools, which includes this change you made.

This is the first "GitHub generated" release of AmpTools.  Could you check to be sure it behaves as you desire?

Matt

**Comment by mikestaib** [comment]
Yep, this release works for me. This will force the requirement for anyone working on the master branch to update versions, but it is a useful functionality. 

@markito3 can we use this for the build tests/default package versions?

**Comment by sdobbs** [comment]
So we can merge this now?

**Comment by mikestaib** [comment]
Can you trigger the build test to see if it works?

**Comment by sdobbs** [comment]
Will do.

**Comment by markito3** [comment]
Won't work. Links do not change until tonight. I'm pretty sure the test build will use old AmpTools, but we will see...

**Comment by sdobbs** [comment]
I'll redo the test tomorrow then... seems like I did not pull the trigger correctly in any case.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/make_OmegaSDMEs.log](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/make_OmegaSDMEs.log)
 Build report: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/report_OmegaSDMEs.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/report_OmegaSDMEs.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^OmegaSDMEs

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/make_OmegaSDMEs.log](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/make_OmegaSDMEs.log)
 Build report: [/work/halld/pull_request_test/sim-recon^OmegaSDMEs/report_OmegaSDMEs.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^OmegaSDMEs/report_OmegaSDMEs.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^OmegaSDMEs

**Pull request merged**
