### PR TITLE
Make CCDB calls in GetObjects() only print information the first time…

### PR DESCRIPTION
**Pull request by sdobbs**
… they are called.

This only affects running over simulated HDDM files.  As requested by Justin.

### CODE REVIEW

**Comment by pmattjlab** [comment]
Technically, this is not thread safe, since all worker threads have access to this method: 2 or more could enter the code block.  Not sure if it's really worth locking though (would slow it down), since it's just a print-to-screen.  Maybe put a comment in there about how bad this is? :)

**Comment by sdobbs** [comment]
That's a good point.  I'll add a comment to that effect.
Hopefully future generations will not be cursing my name...

**Comment by sdobbs** [comment]
FWIW, from the comments it looks like there are a couple places in the class that could use a lock, so I guess that's something to add to the to-do list in some coherent way...

**Comment by pmattjlab** [comment]
Yikes, this is hideous actually.  If two worker threads are on different run numbers, then the "bfield" is bad, etc.  Everything in here that is run-dependent should be done with a map (key = run#) like I did for "dTargetCenterZMap"

**Comment by jrstevenjlab** [comment]
Aside from the larger "thread safeness" issue, do we actually need this printout of the FDC strip_calib table columns at all?  There is already a check if the number of strips is the right size, so it seems like we can remove this printout entirely.

**Comment by staylorjlab** [comment]
We do not need the printout

**Comment by faustus123** [comment]
Paul's right that all of the run-dependent values need to be handled differently if it is going to do the right thing for jobs where more than one run number are encountered. As he suggested, they should be accessed via a map that is protected by a lock.

Of course, one could also just keep the run number around and check that it doesn't change. If it does, then have the program exit with a message saying more than one run number were encountered and if you really need that ability, contact Paul (or just the offline group). This is quick to implement right now and saves having to do a lot of work for something that may or may not really be needed.

**Comment by sdobbs** [comment]
It is pretty unlikely that we would have a simulated data file with multiple runs in it, at this point, so maybe we should just drop the print statement and implement the solution suggested by David?

**Comment by staylorjlab** [comment]
Sounds good to me.

**Comment by sdobbs** [comment]
I've pushed another commit that removes the printout and exits if multiple runs are encountered in the same file.  I expect most people will be just working with REST files, with this format just used as an intermediate step, so it sounds reasonable to me.

How does this look now?

**Comment by pmattjlab** [comment]
You need to initialize the "initialized" value to false in the constructor.

**Comment by sdobbs** [comment]
It should be already.

**Comment by pmattjlab** [comment]
Ah, sorry, it wasn't showing up in the diff, but I guess that's because it was always there.  Merging.

**Comment by pmattjlab** [comment]
For the record, using "initialized" this way isn't thread-safe either ...

**Pull request merged**
