### PR TITLE
Skim bigevents

### PR DESCRIPTION
**Pull request by zihlmann**
skim events that have big numbers of hits in the CDC, > 2000 hits!
these are most likely very high multiplicity cosmic ray events.

Note: this plugin requires to be run with the "evio_writer" plugin

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^skim_bigevents/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^skim_bigevents/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^skim_bigevents/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^skim_bigevents/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^skim_bigevents/make_skim_bigevents.log](https://halldweb.jlab.org/pull_request_test/sim-recon^skim_bigevents/make_skim_bigevents.log)
 Build report: [/work/halld/pull_request_test/sim-recon^skim_bigevents/report_skim_bigevents.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^skim_bigevents/report_skim_bigevents.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^skim_bigevents

**Comment by markdalton** [comment]
Hi Beni,

Where do these events go?

Best,
Mark Macrae Dalton

**Comment by zihlmann** [comment]
I was under the impression they go into a separate evio file that is 
handled by evio_writer plugin.

**Comment by zihlmann** [comment]
in
jerror_t JEventProcessor_bigevents_skim::evnt(JEventLoop *loop, uint64_t 
eventnumber)

there is the line:
     locEventWriterEVIO->Write_EVIOEvent(loop, "bigevents");

so I assume the file is called "bigevents.evio"

but that is only my hope ;-)

**Comment by sdobbs** [comment]
Yes, they go into a separate file, with a additional suffix determined by the argument to e.g. Write_EVIOEvent().  For example, if you analyze hd_rawdata_011261_054.evio, then this plugin will skim events to hd_rawdata_011261_054.bigevents.evio.

These are saved in a local directory, and you are then responsible for saving them in some more-or-less permanent location.

**Pull request merged**
