### PR TITLE
Some fixes for plugins with cosmics

### PR DESCRIPTION
**Pull request by mikestaib**
Fix CDC_Efficiency plugin using field-off tracks. Allow FDCProjectionResiduals to work with field on data.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/make_CDC_Efficiency_Cosmics.log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/make_CDC_Efficiency_Cosmics.log)
 Build report: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/report_CDC_Efficiency_Cosmics.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/report_CDC_Efficiency_Cosmics.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics

**Comment by sdobbs** [comment]
Looks like for the tests to pass, this branch should be merged with the latest master and the tests re-ran

**Comment by mikestaib** [comment]
Yep, See the latest commit. Can you rerun the tests? I tried to follow the steps on the FAQ but I don't think my account has access to the webhooks.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/make_CDC_Efficiency_Cosmics.log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/make_CDC_Efficiency_Cosmics.log)
 Build report: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/report_CDC_Efficiency_Cosmics.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/report_CDC_Efficiency_Cosmics.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics

**Comment by mikestaib** [comment]
In general, shouldn't the procedure on the tests be 

git clone https://www.github.com/JeffersonLab/sim-recon/ 
git merge <branch_name>
- run tests

Given the failure, I think under the hood right now it is probably 
clone->checkout->tests

Wouldn't the first be a better representation of the repository after the PR is merged?

**Comment by sdobbs** [comment]
Oh my bad, I thought the new commit was hanging as well.  When you push changes to a branch, the tests are automagically run again, so that's fine.

The procedure is a policy question - IMO it's the responsibility of developers to keep their branches up to date before merging, but I'm open to discussion.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/make_CDC_Efficiency_Cosmics.log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/make_CDC_Efficiency_Cosmics.log)
 Build report: [/work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/report_CDC_Efficiency_Cosmics.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDC_Efficiency_Cosmics/report_CDC_Efficiency_Cosmics.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^CDC_Efficiency_Cosmics

**Pull request merged**
