### PR TITLE
Copy nsamples_integral into Df125CDCPulse and Df125FDCPulse objects. …

### PR DESCRIPTION
**Pull request by faustus123**
Copy nsamples_integral into Df125CDCPulse and Df125FDCPulse objects Initialize new f125 config. parameters to 0xFFFF.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral/make_davidl_f125_nsamples_integral.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_f125_nsamples_integral/make_davidl_f125_nsamples_integral.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral/report_davidl_f125_nsamples_integral.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_f125_nsamples_integral/report_davidl_f125_nsamples_integral.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral

**Comment by markito3** [comment]
The build failed with:

Cloning into sim-recon^davidl_f125_nsamples_integral...
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/jeffersonlab/sim-recon/info/refs

Is there a way to retrigger the build?

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral/make_davidl_f125_nsamples_integral.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_f125_nsamples_integral/make_davidl_f125_nsamples_integral.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral/report_davidl_f125_nsamples_integral.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_f125_nsamples_integral/report_davidl_f125_nsamples_integral.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral

**Comment by sdobbs** [comment]
For completeness sake, the test build is running now.  It looks like the error @markito3 mentioned is a transitory error in cloning the branch onto the work disk, resulting in an empty file being created instead of a directory containing the source.

**Comment by gluex** [comment]
Build status for this pull request: SUCCESS

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral/make_davidl_f125_nsamples_integral.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_f125_nsamples_integral/make_davidl_f125_nsamples_integral.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral/report_davidl_f125_nsamples_integral.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_f125_nsamples_integral/report_davidl_f125_nsamples_integral.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_f125_nsamples_integral

**Pull request merged**
