### PR TITLE
Updates to mergeTrees.C

### PR DESCRIPTION
**Pull request by abarnes12**
* Fixed secondary chisq branch to be of "F" type
* Changed comparison of reactions

Previously, the comparison of reactions compared any branch with "Plus" with the other reaction's "Plus" branches. This prevented the comparison of PiPlus with Protons. This update ignores the particle type and directly compares the trackID from each reaction.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^aebarnes-chisq/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^aebarnes-chisq/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^aebarnes-chisq/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^aebarnes-chisq/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^aebarnes-chisq/make_aebarnes-chisq.log](https://halldweb.jlab.org/pull_request_test/sim-recon^aebarnes-chisq/make_aebarnes-chisq.log)
 Build report: [/work/halld/pull_request_test/sim-recon^aebarnes-chisq/report_aebarnes-chisq.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^aebarnes-chisq/report_aebarnes-chisq.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^aebarnes-chisq

**Comment by jrstevenjlab** [comment]
Sorry, I missed this before the merge, but does this change still support reactions with photons?  It looks like that flag is turned off in the updated code.

**Comment by abarnes12** [comment]
Whoops, yes, I accidentally disabled that while making it work for proton-antiproton compared with pi+pi-. It would be good to have some neutral trees to test this on. Any recommendation?

**Comment by jrstevenjlab** [comment]
You could try tree_pi0pippim__B3_T4 vs tree_pi0kpkm__B3 from 2017 analysis launch ver08 https://halldweb.jlab.org/wiki-private/index.php/Spring_2017_Analysis_Launch <https://halldweb.jlab.org/wiki-private/index.php/Spring_2017_Analysis_Launch>, which have neutrals, and would let you test the pi+pi- compared to the K+K-

**Pull request merged**
