### PR TITLE
Added TDC digihit output to mcsmear.  Also, fixed issue with HDGEANT …

### PR DESCRIPTION
**Pull request by beattite**
…outputting negative times to unsigned integer structures (digihits).

### CODE REVIEW

**Comment by eltonssmith** [comment]
@faustus123 . Hi Dave, are you the right person to merge this pull request?

**Comment by beattite** [comment]
Sean D. pointed out a potential mistake in the code to me, so I'm going 
to have another closer look at it tomorrow morning, so it may be best to 
hold off on the merge for the moment!

**Comment by beattite** [comment]
A new pull request is up.  I accidentally made a new branch instead of 
pushing to the existing one, so I suppose this request can be closed and 
the other one considered!

**Comment by markito3** [comment]
Closing this one per Tegan's comment. As he points out, the commit is contained in pull request #13.

**Pull request closed without merging**
