### PR TITLE
Set up TPOL_tree plugin for OSG and running off farm

### PR DESCRIPTION
**Pull request by SebsMedDr**
Changed RCDB path to include .jlab.org and changed min peak height for get pulse time function call.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^TPOL/make_TPOL.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/make_TPOL.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TPOL/report_TPOL.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/report_TPOL.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TPOL

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^TPOL/make_TPOL.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/make_TPOL.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TPOL/report_TPOL.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/report_TPOL.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TPOL

**Comment by Sebastian-M-Cole** [comment]
Working on the error now. I do not see this with rcdb 0.02, only with rcdb 0.03

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^TPOL/make_TPOL.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/make_TPOL.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TPOL/report_TPOL.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/report_TPOL.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TPOL

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^TPOL/make_TPOL.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/make_TPOL.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TPOL/report_TPOL.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/report_TPOL.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TPOL

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^TPOL/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^TPOL/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^TPOL/make_TPOL.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/make_TPOL.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TPOL/report_TPOL.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TPOL/report_TPOL.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TPOL

**Pull request merged**
