### PR TITLE
Aaust project moments

### PR DESCRIPTION
**Pull request by aaust**
A program to compute moments from an amptools amplitude fit in mass bins.
Documentation can be found in the talk given at the amplite analysis WG meeting on Nov 6, 2017:
https://halldweb.jlab.org/DocDB/0034/003481/003/aaust_20171106.pdf

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^aaust_project_moments/make_aaust_project_moments.log](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_project_moments/make_aaust_project_moments.log)
 Build report: [/work/halld/pull_request_test/sim-recon^aaust_project_moments/report_aaust_project_moments.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_project_moments/report_aaust_project_moments.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^aaust_project_moments

**Comment by aaust** [comment]
GNU Scientific Library (gsl) is not installed on the machine running the test. We will ask the computing centre to install it and then run the test again.

**Comment by markito3** [comment]
fyi



-------- Forwarded Message --------
Subject: 	CCPR 153564 (installing gsl and gsl-devel on sandd1.jlab.org)
Date: 	Wed, 8 Nov 2017 09:26:47 -0500 (EST)
From: 	ccpr_reply@jlab.org
To: 	marki@jlab.org



This is to verify that your request has been received by the JLab Computer Center.
A copy of it is included below:

Report Number:	153564
Building:	
Room:		
Phone:		
Category:	DESKTOP SUPPORT
Subject:	installing gsl and gsl-devel on sandd1.jlab.org
				
Request:
Dear Helpdesk,

Please install the following RPMs on sandd1.jlab.org:

gsl
gsl-devel .

Thanks in advance.

   - Mark


You can track this or any other help request by going to the searchable database
of problems at: http://mis.jlab.org/mis/apps/ccpr/ccpr_user/ccprframe_user.html?ccpr_requestor_email=marki@jlab.org

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^aaust_project_moments/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_project_moments/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^aaust_project_moments/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_project_moments/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^aaust_project_moments/make_aaust_project_moments.log](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_project_moments/make_aaust_project_moments.log)
 Build report: [/work/halld/pull_request_test/sim-recon^aaust_project_moments/report_aaust_project_moments.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^aaust_project_moments/report_aaust_project_moments.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^aaust_project_moments

**Pull request merged**
