### PR TITLE
First draft of CDC amplitude/gain calibration plugin (from nsj)

### PR DESCRIPTION
**Pull request by sdobbs**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/make_sdobbs_CDC_amp.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/make_sdobbs_CDC_amp.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/report_sdobbs_CDC_amp.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/report_sdobbs_CDC_amp.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp

**Comment by sdobbs** [comment]
Hm, note that the past ~7 test builds have actually not run! The build system has been sped up, but build times are not <1 minute.  Investigating...

**Comment by sdobbs** [comment]
OK, it's running now...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/make_sdobbs_CDC_amp.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/make_sdobbs_CDC_amp.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp/report_sdobbs_CDC_amp.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_CDC_amp/report_sdobbs_CDC_amp.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_CDC_amp

**Comment by markito3** [comment]
What was the issue with non-running builds?

**Comment by sdobbs** [comment]
The command to actually run the test build was commented out.  Not sure if it was my fault or if a change got wrongly reapplied at some point.

**Pull request merged**
