### PR TITLE
FDC Histograms for occupancy_online

### PR DESCRIPTION
**Pull request by mikestaib**
Add FDC Histograms using FDCPseudo hits and associated RootSpy macros

### CODE REVIEW

**Comment by pmattjlab** [comment]
Can we use digi hits instead?  It's the most raw level, and it's what all the other systems are using.  Or is it inappropriate somehow?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^FDCOcc/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^FDCOcc/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^FDCOcc/make_FDCOcc.log](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/make_FDCOcc.log)
 Build report: [/work/halld/pull_request_test/sim-recon^FDCOcc/report_FDCOcc.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/report_FDCOcc.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^FDCOcc

**Comment by mikestaib** [comment]
Hmm, I could see arguments either way. This way is nice because it compresses 2 cathode layers and one wire layer together into one plot and it's easy to tell which is missing. However, this requires some quality of the calibrations to make sure the timings agree. These cuts are extremely loose for now so it's not very strongly dependent on the calibrations at all.

Motivation for this way:  This is what Lubomir asked for at the FDC meeting yesterday.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^FDCOcc/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^FDCOcc/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^FDCOcc/make_FDCOcc.log](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/make_FDCOcc.log)
 Build report: [/work/halld/pull_request_test/sim-recon^FDCOcc/report_FDCOcc.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^FDCOcc/report_FDCOcc.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^FDCOcc

**Pull request merged**
