### PR TITLE
Reduce size of PS flux trees and other tweaks

### PR DESCRIPTION
**Pull request by jrstevenjlab**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/make_ps_flux_reduce_size.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/make_ps_flux_reduce_size.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/report_ps_flux_reduce_size.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/report_ps_flux_reduce_size.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ps_flux_reduce_size

**Comment by jrstevenjlab** [comment]
The test build seems to have failed in the TRIGGER library which wasn't changed.  Suggestions?

**Comment by sdobbs** [comment]
The ever popular "internal compiler error".  Likely this is some transient
ifarm problem, let me start the build again...

**Comment by staylorjlab** [comment]
How many build threads are we using?  We are now restricted to 8 
processes on the ifarm machines.

Simon

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/make_ps_flux_reduce_size.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/make_ps_flux_reduce_size.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/report_ps_flux_reduce_size.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/report_ps_flux_reduce_size.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ps_flux_reduce_size

**Comment by sdobbs** [comment]
We are using 8 threads, let me try reducing this.

Is this 8 processes/threads per user?  Was this annouced anywhere?

**Comment by staylorjlab** [comment]
Beni and I just noticed that our builds were being killed on the 
ifarm... I don't remember seeing a notice.

**Comment by sdobbs** [comment]
Thanks, another bullet point in my crusade against the poor communication coming out of the computer room =)

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/make_ps_flux_reduce_size.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/make_ps_flux_reduce_size.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ps_flux_reduce_size/report_ps_flux_reduce_size.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ps_flux_reduce_size/report_ps_flux_reduce_size.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ps_flux_reduce_size

**Pull request merged**
