### PR TITLE
* This is a coordinated update to the way electromagnetic background

### PR DESCRIPTION
**Pull request by rjones30**
is simulated in hdgeant. There are three major changes included:
   1) Fix a bug in gukine that made the simulation generate far
      too many background photons when the value of bgrate rose
      to the level near 1/beam_period_ns. This was a very severe
      bug, introduced in a recent change I made, which made the
      em bg simulation all but useless in hdgeant. This restores
      the former correct functioning of this feature.
   2) Introduce a new feature requested by Sean Dobbs that allows
      the simulation to generate accidental tags from out-of-time beam
      photons without paying the full price of tracking them through
      the detector. This option is now implemented as a new card in
      control.in called BGTAGONLY which has a single integer field,
      either zero (former behavior) or non-zero (new behavior).
   3) Improve the efficiency of the bg photons generator in hdgeant.
      The former code generated energy and polarization spectra with
      the correct distributions, but it was not very efficient in that
      most of the trial gammas generated were discarded by a harsh
      keep/reject threshold. This is now better tuned, and also more
      less likely to generate warnings about freqMaximum being exceeded.

* control.in [rtj]
   - add new card BGTAGONLY with comment
   - add a more helpful comment for the BGRATE card

* backgrounds.inc, uginit.F [rtj]
   - add support for the new card BGTAGONLY

* gukine.F [rtj]
   - fix the bug mentioned above that caused the rate of generated
     bg beam photons to diverge as the bgrate approached 1/beam_period_ns.

* beamgen.F [rtj]
   - improvements to the efficiency of the importance sampling algorithm
     that is used to sample the coherent bremsstrahlung distribution

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj

**Comment by sdobbs** [comment]
Let's try this test build again..

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/make_hdgeant_em_bg_sim_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj/report_hdgeant_em_bg_sim_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hdgeant_em_bg_sim_fixes_rtj

**Pull request merged**
