### PR TITLE
Hddm parallel io rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj

**Comment by sparksn** [comment]
A CentOS 6 build of this branch succeeded for me.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj

**Comment by faustus123** [comment]
This looks like a generated file from ROOT in hdview2. Does this have to do with a recent change to the
ROOT version being used for these builds?

**Comment by sdobbs** [comment]
In talking to Mark Ito, this might a ROOT6-related build fix that was not
correctly propogated.  I am checking this out now..

**Comment by gluex** [comment]
Test status for this pull request: FAILURE

 Failures: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/make_hddm_parallel_io_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^hddm_parallel_io_rtj/report_hddm_parallel_io_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^hddm_parallel_io_rtj

**Comment by sdobbs** [comment]
Sorry, ignore these last messages.  Test builds should be working again.

**Comment by gvasil** [comment]
I don't know if the following are related to this pull request, but:

I tried to build sim-recon-2.4.0  (ROOT 6) on JLab CUE and it works.

I tried to build sim-recon-2.5.0  (ROOT 6) and it returns the following error:

HDDM-PY    [libraries/HDDM/rest.xml]
In file included from pyhddm_mc_s.cxx:23:0:
/lustre/expphy/work/halld/home/gvasil/halld/builds/sim-recon/sim-recon-2.5.0/src/.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_mc_s.hpp: In member function 'hddm_mc_s::ostream& hddm_mc_s::ostream::operator<<(hddm_mc_s::HDDM&)':
/lustre/expphy/work/halld/home/gvasil/halld/builds/sim-recon/sim-recon-2.5.0/src/.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_mc_s.hpp:1338:62: error: 'class xstream::bz::ostreambuf' has no member named 'get_block_start'
       MY(last_start) = ((xstream::bz::ostreambuf_)MY(xcmp))->get_block_start();
                                                              ^
/lustre/expphy/work/halld/home/gvasil/halld/builds/sim-recon/sim-recon-2.5.0/src/.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_mc_s.hpp:1342:61: error: 'class xstream::z::ostreambuf' has no member named 'get_block_start'
       MY(last_start) = ((xstream::z::ostreambuf_)MY(xcmp))->get_block_start();
                                                             ^
PYMODBUILD [.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/setup_hddm_r.py]
error: command 'gcc' failed with exit status 1
scons: **\* [.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_mc_s.so] Error 1
In file included from pyhddm_r.cxx:23:0:
/lustre/expphy/work/halld/home/gvasil/halld/builds/sim-recon/sim-recon-2.5.0/src/.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_r.hpp: In member function 'hddm_r::ostream& hddm_r::ostream::operator<<(hddm_r::HDDM&)':
/lustre/expphy/work/halld/home/gvasil/halld/builds/sim-recon/sim-recon-2.5.0/src/.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_r.hpp:2571:62: error: 'class xstream::bz::ostreambuf' has no member named 'get_block_start'
       MY(last_start) = ((xstream::bz::ostreambuf_)MY(xcmp))->get_block_start();
                                                              ^
/lustre/expphy/work/halld/home/gvasil/halld/builds/sim-recon/sim-recon-2.5.0/src/.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_r.hpp:2575:61: error: 'class xstream::z::ostreambuf' has no member named 'get_block_start'
       MY(last_start) = ((xstream::z::ostreambuf_)MY(xcmp))->get_block_start();
                                                             ^
error: command 'gcc' failed with exit status 1
scons: **\* [.Linux_CentOS6-x86_64-gcc4.9.2/libraries/HDDM/hddm_r.so] Error 1
scons: building terminated because of errors.

**Comment by markito3** [comment]
George,
What version of Python are you using?

At JLab, what works for me is

```
# python on the cue
export PATH=/apps/python/PRO/bin:$PATH
export LD_LIBRARY_PATH=/apps/python/PRO/lib:$LD_LIBRARY_PATH
```

These lines are contained in [gluex_env_jlab.sh](https://github.com/JeffersonLab/build_scripts/blob/master/gluex_env_jlab.sh).

**Comment by gvasil** [comment]
Hi Mark,

I am also sourcing gluex_env_jlab.sh. What troubles me is that the tagged release 2.4.0 compiles without errors.

In any case, if nobody else faces compilation issues with sim-recon-2.5.0 then there is probably something wrong with my configuration. I will try to figure it out.

Thank you,
George

**Pull request merged**
