### PR TITLE
REST metadata and skim updates

### PR DESCRIPTION
**Pull request by sdobbs**
- Modify MC & REST formats to store CCDB context and data version tag info
- Change DEventWriterREST to fill these fields
- Add e+e- skims

### CODE REVIEW

**Comment by pmattjlab** [comment]
No, this skim is bad.  You only make one blueprint, then you cut it.  If you're gonna cut, you should make all of them.  You're throwing a lot of events away.

**Comment by pmattjlab** [comment]
Use the set any combo flag instead.  And add your action as a pre-combo cut action.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/make_sdobbs_rest_and_skim_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/make_sdobbs_rest_and_skim_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/report_sdobbs_rest_and_skim_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/report_sdobbs_rest_and_skim_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates

**Comment by sdobbs** [comment]
OK, thanks, how does this look now?

**Comment by pmattjlab** [comment]
Looks good.  Although that Jpsi mass cut is ridiculously wide.  Do you really need it that wide?  The skim could be a lot smaller, I suspect.

**Comment by sdobbs** [comment]
Well, it's really a "high-mass e+e- pair" cut at the moment.  The skim should be pretty small, so I think it's good for now.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/make_sdobbs_rest_and_skim_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/make_sdobbs_rest_and_skim_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/report_sdobbs_rest_and_skim_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates/report_sdobbs_rest_and_skim_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_rest_and_skim_updates

**Pull request merged**
