### PR TITLE
New online plugin for BCAL LED data

### PR DESCRIPTION
**Pull request by markdalton**
A new plugin for use with the online and offline monitoring systems which
analyzes the BCAL LED data.

It works but need significant improvement.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/make_dalton_plugin_BCAL_LEDonline.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/make_dalton_plugin_BCAL_LEDonline.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/report_dalton_plugin_BCAL_LEDonline.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline/report_dalton_plugin_BCAL_LEDonline.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_plugin_BCAL_LEDonline

**Comment by sparksn** [comment]
@markdalton 
This fails to build when using ROOT-6, because ROOT-6 has removed `TH1::kCanRebin`.
I am not sure how to handle this in a way that works for both ROOT-5 and 6. Has anyone
else encountered this issue?

**Comment by markdalton** [comment]
Hi,

This is an interesting point.  ROOT-6 does have a way to accomplish the same thing, but the method has a different name.  So, is there a way for me to write code that will use one thing if compiled with ROOT-6 and another with ROOT-5?  Something with compiler directives maybe?

Best,
Mark Macrae Dalton

**Comment by rjones30** [comment]
Hello Mark and all,

 #if ROOT_VERSION_CODE >= ROOT_VERSION(6,0,0)
    // stuff for root 6 or greater
 #else
    // stuff for versions of root prior to 6
 #endif

-Richard Jones

**Pull request merged**
