### PR TITLE
DBCALGeometry refactoring

### PR DESCRIPTION
**Pull request by sdobbs**
First round of refactoring of DBCALGeometry (there will be more).

- Removed static members, changed user classes to always retrieve object properly on a run-dependent basis, cleaned up the worst offenders.
- Started creating better interface and removed some unneeded code.
- Changed redundant constant PI to M_PI

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/make_sdobbs_bcal_geom_refactor.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/make_sdobbs_bcal_geom_refactor.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/report_sdobbs_bcal_geom_refactor.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/report_sdobbs_bcal_geom_refactor.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor

**Comment by pmattjlab** [comment]
This no longer looks hideous.  Thank you!

**Comment by sdobbs** [comment]
Also is no longer a cause of sneakily buggy output!

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/make_sdobbs_bcal_geom_refactor.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/make_sdobbs_bcal_geom_refactor.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/report_sdobbs_bcal_geom_refactor.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor/report_sdobbs_bcal_geom_refactor.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_bcal_geom_refactor

**Pull request merged**
