### PR TITLE
update monitoring plugin

### PR DESCRIPTION
**Pull request by nsjarvis**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/make_nsj_CDC_roc_hits_update.log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/make_nsj_CDC_roc_hits_update.log)
 Build report: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/report_nsj_CDC_roc_hits_update.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/report_nsj_CDC_roc_hits_update.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/make_nsj_CDC_roc_hits_update.log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/make_nsj_CDC_roc_hits_update.log)
 Build report: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/report_nsj_CDC_roc_hits_update.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/report_nsj_CDC_roc_hits_update.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update

**Comment by markito3** [comment]
I merged in changes from the master (there were 90 changed files) and pushed them to GitHub. Test build running now...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/make_nsj_CDC_roc_hits_update.log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/make_nsj_CDC_roc_hits_update.log)
 Build report: [/work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/report_nsj_CDC_roc_hits_update.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_roc_hits_update/report_nsj_CDC_roc_hits_update.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^nsj_CDC_roc_hits_update

**Comment by nsjarvis** [comment]
Ninety?  (quiet whimper).

Thank you.

**Pull request merged**
