### PR TITLE
Several changes to macros so that they wouldn't throw errors in the offline monitoring

### PR DESCRIPTION
**Pull request by sdobbs**
- HistMacro_NumLowLevelObjects_p2.C - fixed a few times the axis wasn't properly referenced
- ST_Monitoring_Eff.C - cast TDirectoryFile -> TDirectory;  fixed some error checking
- ST_online_tracking: commented out debugging information

### CODE REVIEW

**Comment by markito3** [comment]
@KMahmoud or @pooser : one of you guys wanna review this pull request?

**Comment by pooser** [comment]
It looks good to me.

**Comment by markito3** [comment]
Sean,

The thing where I mentioned Mahmoud and Eric without merging your request is me just trying out what we can do with the system. If your changes are not merged soon, I'll go ahead and merge them myself. If you need the merge sooner than soon, let me know or just go ahead and do the merge yourself.

  -- Mark

----- Original Message -----

**Comment by markito3** [comment]
@pooser : go ahead and do the merge...then we know who to blame! ;-)

**Comment by sdobbs** [comment]
@markito3 Cool, I'm liking this!  Maybe we should set up a twitter channel to broadcast when the nightly builds succeed or fail =)
@pooser Thanks!

**Comment by pooser** [comment]
@markito3 the deed is done!  This is much cooler than svn ;-)

**Pull request merged**
