### PR TITLE
Reject large changes in TAGH counter-counter offsets

### PR DESCRIPTION
**Pull request by sparksn**
Subtract off offset of counter 1 so its individual offset is always 0.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^ns_TAGH_offsets/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TAGH_offsets/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ns_TAGH_offsets/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TAGH_offsets/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^ns_TAGH_offsets/make_ns_TAGH_offsets.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TAGH_offsets/make_ns_TAGH_offsets.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_TAGH_offsets/report_ns_TAGH_offsets.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_TAGH_offsets/report_ns_TAGH_offsets.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_TAGH_offsets

**Comment by pmattjlab** [comment]
Don't hardcode the beam bunch frequency (4ns).  Get it from the CCDB instead.  See for example an analysis plugin (e.g. p2pi_hists).

**Comment by sparksn** [comment]
`limit` is not strictly speaking the beam bunch period.
It is the maximum allowed difference with the most frequent change in offset.
`4 ns` is just a conservative value to start with.

**Comment by pmattjlab** [comment]
As long as you know what you're doing.

**Comment by markito3** [comment]
Gosh, I do hope he knows what he is doing! ;-)

**Comment by sdobbs** [comment]
Does this mean that we have to fix the occasional ~30 ns TDC shifts by hand?

**Comment by sparksn** [comment]
Yes, it does.
If those shifts continue to happen on a regular basis, I will write a script to correct them.

**Comment by sdobbs** [comment]
Yes, they are expected to.  Is it worth trying to special-case them here?
Maybe looking for something specifically of that magnitude?  Or if we
assume that in the track-based alignment that the ADCs and TDCs should be
aligned within your delta, you could check to see if there's a difference
between the updated ADC and TDC of ~30 ns?

**Comment by sparksn** [comment]
Okay, that is annoying. I was hoping that problem would go away or be reduced.
From what I remember, it happened in about 10 production runs last Spring.

The shifts happen for blocks of 32 counters, and the shift in time is about 32 ns.
These features could be used to detect the shifts in HLDetectorTiming.
I will think about how to handle it.

**Comment by sdobbs** [comment]
Yeah, it is related to how the F1TDCs pick up the clock signal and there is
apparently no easy solution, so we will have to take care of it in software
for now.

**Pull request merged**
