### PR TITLE
Bug fixes. Now histograms are produced with channel numbers that matc…

### PR DESCRIPTION
**Pull request by adesh-subedi**
Bug fixes. Now histograms are produced with channel numbers that match ccdb numbering.

### CODE REVIEW

**Comment by sparksn** [comment]
@sdobbs 
The build and tests were successful but the comment POST returned a `405 Not Allowed`.
Have you seen this before?

**Comment by sdobbs** [comment]
No, I haven't.  It sounds like it could be a transient error.  Maybe try
redoing the build and see if the error reoccurs?

**Comment by sparksn** [comment]
You are probably correct about it being a transient error;
It did not occur for the next PR test. I say we let it be for now.

**Comment by sdobbs** [comment]
Fine with me.

**Pull request merged**
