### PR TITLE
DBCALPoint c_effective fix

### PR DESCRIPTION
**Pull request by beattite**
Changes the DBCALPoint constructor to accept 'c_effective' as an input so that the CCDB values can be used rather than DBCALGEOMETRY::C_EFFECTIVE (an outdated constant).

### CODE REVIEW

**Comment by beattite** [comment]
Sorry, there is an error (I wasn't meant to add the change to the eventfilter)!  Will re-submit the request briefly.

**Comment by sdobbs** [comment]
Actually, can you leave the branch up without making a PR so that I can run some tests first?  
Feel free to make any changes to the branch in the meanwhile.

**Comment by beattite** [comment]
Okay, sure.  I'm slowly learning how this Git thing works!

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^DBCALPoint_c_eff_fix/make_DBCALPoint_c_eff_fix.log](https://halldweb.jlab.org/pull_request_test/sim-recon^DBCALPoint_c_eff_fix/make_DBCALPoint_c_eff_fix.log)
 Build report: [/work/halld/pull_request_test/sim-recon^DBCALPoint_c_eff_fix/report_DBCALPoint_c_eff_fix.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^DBCALPoint_c_eff_fix/report_DBCALPoint_c_eff_fix.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^DBCALPoint_c_eff_fix

**Pull request closed without merging**
