### PR TITLE
New plugin to record pedestal as a function of time for individual crates.

### PR DESCRIPTION
**Pull request by markdalton**
New plugin to record pedestal as a function of time for individual crates.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/make_dalton_plugin_pedestal_online.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/make_dalton_plugin_pedestal_online.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/report_dalton_plugin_pedestal_online.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/report_dalton_plugin_pedestal_online.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online

**Comment by sdobbs** [comment]
Please ignore automated test results for now... I'll fix the problem...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/make_dalton_plugin_pedestal_online.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/make_dalton_plugin_pedestal_online.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/report_dalton_plugin_pedestal_online.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/report_dalton_plugin_pedestal_online.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/make_dalton_plugin_pedestal_online.log](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/make_dalton_plugin_pedestal_online.log)
 Build report: [/work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online/report_dalton_plugin_pedestal_online.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^dalton_plugin_pedestal_online/report_dalton_plugin_pedestal_online.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^dalton_plugin_pedestal_online

**Comment by sdobbs** [comment]
And we're back!

**Pull request merged**
