### PR TITLE
Davidl plugin linking

### PR DESCRIPTION
**Pull request by faustus123**
This implements what was discussed at the Wed. Mar. 22, 2017 Offline meeting. Namely:

1. Static sim-recon libraries are no longer linked directly into executables. Those routines are taken from the compiled executable (e.g. hd_root)

2. Several plugins demoted to "optionally build" and several old programs removed completely.
(n.b. the old programs were mostly things that have not been compiled since we switched from "make" to "scons" years ago)

The plugins were checked to still work on CentOS 6.5, CentOS 7.1 and Mac OS X 10.11.
Most recent test on CentOS7.1 worked with hd_root running each of the following plugins:

highlevel_online
danarest
evio_writer,ps_skim

The last line above required both plugins in that order since ps_skim uses features in evio_writer. (This combo may have always been required, but thought I would note it here anyway.)

### CODE REVIEW

**Comment by sdobbs** [comment]
The directory used for the pull request test is having some trouble which is stalling the test build. 
I submitted a CCPR, and will merge this PR, assuming that the offline tests are fine.

**Comment by sparksn** [comment]
I successfully did a build and ran some plugins on my RHEL 7 machine for this PR.
I believe we ran out of memory during the test build on the Farm.

**Comment by sdobbs** [comment]
I'm having problems accessing several directories, so it could be a disk
issue as well.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_plugin_linking/make_davidl_plugin_linking.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_plugin_linking/make_davidl_plugin_linking.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_plugin_linking/report_davidl_plugin_linking.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_plugin_linking/report_davidl_plugin_linking.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_plugin_linking

**Comment by markito3** [comment]
Guys, I thought this was the one pull request, of all pull requests, where we wanted to wait for a test success before merging, no?

**Comment by sdobbs** [comment]
"Trust, but verify", eh?  The build failed due to the disk I/O issues I mentioned earlier, which lasted most of the day.  I just started a new test build to be safe.

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^davidl_plugin_linking/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_plugin_linking/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^davidl_plugin_linking/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_plugin_linking/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_plugin_linking/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_plugin_linking/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_plugin_linking/make_davidl_plugin_linking.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_plugin_linking/make_davidl_plugin_linking.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_plugin_linking/report_davidl_plugin_linking.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_plugin_linking/report_davidl_plugin_linking.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_plugin_linking

**Comment by sdobbs** [comment]
@NathanSparks, can you tell why the TOF_online test failed (the only one?).
The log looks fine to me... https://halldweb.jlab.org/pull_request_test/sim-recon%5edavidl_plugin_linking/tests-logs/TOF_online.txt

**Comment by sparksn** [comment]
No, not really...
CDC_expert failed in the same way a couple of days ago.
From the output in the log file, it looks like TOF_online did not close the output ROOT file before exiting.
I wanted to conclude that the job timed out (> 3 min.) but the log file timestamps seem to suggest otherwise. Let's blame it on Lustre.

**Comment by sdobbs** [comment]
I think we are supposed to blame the network rather than the file system =)

**Comment by sparksn** [comment]
Okay, Okay... that blasted LNet.

**Pull request merged**
