### PR TITLE
Do not merge: This PR is for testing the PR tests

### PR DESCRIPTION
**Pull request by sparksn**
Syntax errors were added to a few plugin src files.
The PR test should fail at the build stage, and show a build status of FAILURE.

### CODE REVIEW

**Comment by sparksn** [comment]
The build did not start up properly; probably due to the "/"'s in the branch name. An effort was made to convert them to underscores in the scripts when necessary, but apparently, something was missed.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests/make_ns_test_the_PR-tests.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_test_the_PR-tests/make_ns_test_the_PR-tests.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests/report_ns_test_the_PR-tests.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_test_the_PR-tests/report_ns_test_the_PR-tests.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests

**Comment by sparksn** [comment]
The missing conversion of slashes was in the ssh wrapper script. 
As expected, the build failed, and the gluex comment shows the correct status and logs.

**Comment by gluex** [comment]
Test status for this pull request: FAILURE

 Failures: [/work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_test_the_PR-tests/tests/failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_test_the_PR-tests/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_test_the_PR-tests/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests/make_ns_test_the_PR-tests.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_test_the_PR-tests/make_ns_test_the_PR-tests.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests/report_ns_test_the_PR-tests.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_test_the_PR-tests/report_ns_test_the_PR-tests.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_test_the_PR-tests

**Pull request closed without merging**
