### PR TITLE
Fixes related to mcsmear rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/make_fixes_related_to_mcsmear_rtj.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj/report_fixes_related_to_mcsmear_rtj.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fixes_related_to_mcsmear_rtj

**Comment by markito3** [comment]
Yay!

**Pull request merged**
