### PR TITLE
Fix root crash

### PR DESCRIPTION
**Pull request by pmattjlab**
To create histograms in memory, do NOT create them in gROOT->cd().  This causes crashes at program exit.  Instead, call TH1::SetDirectory(nullptr).  Thus ends the 2 week saga.  

Also, fix minor bug about no default value for a parameter.

### CODE REVIEW

**Comment by pmattjlab** [comment]
This will conflict with Will's recent pull request.  Will merge and resubmit.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^fix_root_crash/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^fix_root_crash/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^fix_root_crash/make_fix_root_crash.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/make_fix_root_crash.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fix_root_crash/report_fix_root_crash.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/report_fix_root_crash.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fix_root_crash

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^fix_root_crash/make_fix_root_crash.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/make_fix_root_crash.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fix_root_crash/report_fix_root_crash.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/report_fix_root_crash.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fix_root_crash

**Comment by pmattjlab** [comment]
Ha, found a bug with the testing system.

Will, please double check to make sure that your changes are present in my merge.

**Comment by wmcginle** [comment]
The changes I made are present in your merge.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^fix_root_crash/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^fix_root_crash/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^fix_root_crash/make_fix_root_crash.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/make_fix_root_crash.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fix_root_crash/report_fix_root_crash.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fix_root_crash/report_fix_root_crash.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fix_root_crash

**Comment by sdobbs** [comment]
Bug report?

**Comment by pmattjlab** [comment]
I guess it auto-deleted the log file, but:

I closed the merge request while the build was ongoing.  I quickly made a change, re-pushed the branch, and reopened the pull request.  The build test immediately failed, with the error message saying something to the effect that the directory it wanted to use already exists, I guess because it hadn't been cleaned up yet from the first test.

**Pull request merged**
