### PR TITLE
TS scalers in the DL1Trigger back

### PR DESCRIPTION
**Pull request by somovalex**
Parse and add TS scalers to the DL1Trigger bank

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^master/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^master/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^master/make_master.log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/make_master.log)
 Build report: [/work/halld/pull_request_test/sim-recon^master/report_master.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/report_master.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^master

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^master/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^master/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^master/make_master.log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/make_master.log)
 Build report: [/work/halld/pull_request_test/sim-recon^master/report_master.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/report_master.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^master

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^master/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^master/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^master/make_master.log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/make_master.log)
 Build report: [/work/halld/pull_request_test/sim-recon^master/report_master.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/report_master.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^master

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^master/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^master/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^master/make_master.log](https://halldweb.jlab.org/pull_request_test/sim-recon^master/make_master.log)
 Build report: [/work/halld/pull_request_test/sim-recon^master/report_master.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^master/report_master.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^master

**Comment by markito3** [comment]
This pull request seems backward to me, a request to merge from master to new branch. Closing it.

**Pull request closed without merging**
