### PR TITLE
Add RCDB environment to generated setenv scripts.

### PR DESCRIPTION
**Pull request by faustus123**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv/make_davidl_RCDB_setenv.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_RCDB_setenv/make_davidl_RCDB_setenv.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv/report_davidl_RCDB_setenv.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_RCDB_setenv/report_davidl_RCDB_setenv.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv

**Comment by sdobbs** [comment]
The build failure was due to a disk error - I'm going to re-run the build anyway to test if this PR fixes something with the test build environment, but am merging it anyway.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_RCDB_setenv/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_RCDB_setenv/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv/make_davidl_RCDB_setenv.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_RCDB_setenv/make_davidl_RCDB_setenv.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv/report_davidl_RCDB_setenv.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_RCDB_setenv/report_davidl_RCDB_setenv.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_RCDB_setenv

**Comment by sdobbs** [comment]
:+1:

**Pull request merged**
