### PR TITLE
Add definitions for alignas and std::accumulate 

### PR DESCRIPTION
**Pull request by faustus123**
This allows sim-recon to be built on Mac OS X whose Apple LLVM version 8.0.0 (clang-800.0.38) compiler does not support alignas or std:accumulate. It should not affect systems where the compiler defines these.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_macosx/make_davidl_macosx.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/make_davidl_macosx.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_macosx/report_davidl_macosx.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/report_davidl_macosx.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_macosx

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^davidl_macosx/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_macosx/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_macosx/make_davidl_macosx.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/make_davidl_macosx.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_macosx/report_davidl_macosx.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/report_davidl_macosx.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_macosx

**Comment by faustus123** [comment]
Made some changes which *may* fix things. Will let auto-build of pull request be definitive test.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^davidl_macosx/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_macosx/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_macosx/make_davidl_macosx.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/make_davidl_macosx.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_macosx/report_davidl_macosx.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_macosx/report_davidl_macosx.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_macosx

**Pull request merged**
