### PR TITLE
Fix tagger and PS pedestal calculations

### PR DESCRIPTION
**Pull request by sparksn**
Fix the calculation of the average pedestal and rearrange some code
in order to make the pedestal subtraction easier to follow.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_average_pedestal

**Comment by sparksn** [comment]
A commit was added to fix and refactor the FCAL and SC pedestal subtractions.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_average_pedestal

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_average_pedestal

**Comment by sparksn** [comment]
Another commit was added to take into account that digihit->pulse_peak is properly set for the old data source too. This allows the branching on the data source to be removed.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/make_ns_average_pedestal.log)
 Build report: [/work/halld/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^ns_average_pedestal/report_ns_average_pedestal.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^ns_average_pedestal

**Pull request merged**
