### PR TITLE
Print out the pulse peak for f250 digihits

### PR DESCRIPTION
**Pull request by sdobbs**
...now that it is being generated by the new firmware.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE

 Failures: [/work/halld/pull_request_test/sim-recon^sdobbs_digihit_updates/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_digihit_updates/tests/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^sdobbs_digihit_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_digihit_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^sdobbs_digihit_updates/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_digihit_updates/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_digihit_updates/make_sdobbs_digihit_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_digihit_updates/make_sdobbs_digihit_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_digihit_updates/report_sdobbs_digihit_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_digihit_updates/report_sdobbs_digihit_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_digihit_updates

**Comment by sdobbs** [comment]
Just failed the BCAL_Eff test.  Checking...

**Comment by sparksn** [comment]
Looks okay to me.

**Comment by sdobbs** [comment]
Thanks, yeah, it looks like the test just timed out.

**Pull request merged**
