### PR TITLE
 Use correct channel summing over SiPMs resolution from ccdb in the B…

### PR DESCRIPTION
**Pull request by wmcginle**
…CAL smearing code

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^BCALSmearing/make_BCALSmearing.log](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/make_BCALSmearing.log)
 Build report: [/work/halld/pull_request_test/sim-recon^BCALSmearing/report_BCALSmearing.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/report_BCALSmearing.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^BCALSmearing

**Comment by mikestaib** [comment]
Looks like filesystem errors. Maybe we are exceeding our work allocation? 

https://halldweb.jlab.org/disk_management/work_report.html

**Comment by mikestaib** [comment]
Mark had contacted scicomp, and they believe we should have room. @sdobbs can maybe relaunch and see?

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^BCALSmearing/make_BCALSmearing.log](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/make_BCALSmearing.log)
 Build report: [/work/halld/pull_request_test/sim-recon^BCALSmearing/report_BCALSmearing.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/report_BCALSmearing.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^BCALSmearing

**Comment by sdobbs** [comment]
It's a problem with ifarm1102 (where we run the test build).  I'm submitting a CCPR...

**Comment by sdobbs** [comment]
The machine was rebooted and the test build is progressing.

I am confused about this commit, though.  It looks like you're trying to grab a parameter named "BCAL_TWO_HIT_RESO", but I don't see anything of that name in /BCAL/bcal_parms

**Comment by wmcginle** [comment]
The parameter "BCAL_TWO_HIT_RESO" is in the /BCAL/bcal_smear_parms table.

**Comment by sdobbs** [comment]
Ah, okay, I see what you did now.  Is /BCAL/bcal_parms being used anywhere?  HDGeant?

**Comment by wmcginle** [comment]
Some of the elements of BCAL/bcal_parms are used in the HDGeant HitBCal.cc file.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^BCALSmearing/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^BCALSmearing/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/tests-logs)

 Build log: [/work/halld/pull_request_test/sim-recon^BCALSmearing/make_BCALSmearing.log](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/make_BCALSmearing.log)
 Build report: [/work/halld/pull_request_test/sim-recon^BCALSmearing/report_BCALSmearing.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^BCALSmearing/report_BCALSmearing.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^BCALSmearing

**Pull request merged**
