### PR TITLE
Updates to support MC trigger studies

### PR DESCRIPTION
**Pull request by sdobbs**
- Updated MCTrigger factory to calculate trigger-style BCAL and FCAL hit energy sums with per-channel thresholds.  These are found to be different than the sum of all shower energies.
- BCAL & FCAL energy sums saved in REST format

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: SUCCESS

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates

**Comment by pmattjlab** [comment]
Instead of creating a new base-level REST object "trigger_v2," you could instead create a sub-tag within "trigger," similar to how I added "mcmatch" to "chargedTrack."  Not sure how much it matters though.

**Comment by sdobbs** [comment]
Okay, I could do that, although maybe it's overcomplicating the object?  I don't really have a good feeling for what is preferred.

**Comment by pmattjlab** [comment]
I'm not sure either.  However, you should probably update DEventSourceREST.  Make sure to leave it backwards compatible.

**Comment by sdobbs** [comment]
Hm, I see what you mean.  The nested tags seem to make the code a bit simpler, so I'll change to that.

**Comment by gluex** [comment]
Build status for this pull request: SUCCESS

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates

**Comment by sdobbs** [comment]
OK, I've updated the branch using nested tags.  
One lingering question in my mind is if it's more useful to save TOF hits or TOF points.  Maybe @markito3 has some thoughts on this?

**Comment by gluex** [comment]
Build status for this pull request: SUCCESS

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates

**Comment by sdobbs** [comment]
Please ignore any more comments from gluex - I'm testing a new feature.
Branch is still ready to be merged.

**Comment by gluex** [comment]
Build status for this pull request: SUCCESS

 Build log: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/make_sdobbs_mctrigger_updates.log)
 Build report: [/work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^sdobbs_mctrigger_updates/report_sdobbs_mctrigger_updates.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^sdobbs_mctrigger_updates

**Pull request merged**
