### PR TITLE
copy DCDCHit factory into new factory with Tag "Calib". remove the QF…

### PR DESCRIPTION
**Pull request by zihlmann**
… bit timing cut

and the drift time cut from this Taged factory and move these two cuts into the new
DCDCHit factory. Add a pruing algorithm to the DCDCHit factory that removes hits from
the list that are correlated with a hit that has overflow on the same connector.

### CODE REVIEW

**Comment by zihlmann** [comment]
This change follows a similar approach as is done in the TAGGER hit factory.
cuts to remove hits from the CDC hit list are applied after the main hit list is created
using the tag "Calib". In this way expert code can access the CDC hits before cuting
some away depending on the timing quality, timing and correlation with saturation hits
withing the same connector/hvboard/preamp.
The QF bits are added to the DCDCHit container.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/make_CDCHitFactoryUpdate.log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/make_CDCHitFactoryUpdate.log)
 Build report: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/report_CDCHitFactoryUpdate.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/report_CDCHitFactoryUpdate.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate

**Comment by sdobbs** [comment]
A couple quick comments before merging:

1) Can we make all of these large arrays vectors instead?
2) Can the 3.5 ns timing cut for correlated hits be a parameter as well?

**Comment by nsjarvis** [comment]
Hey Beni,

Are you sure that the cut should start at exactly 3.5 samples?   I thought
it looked more like 2 to 3 samples.

While you're doing this, you might want to add some code to cut out the
impossible events where many channels on the same hvb have hits in the same
time-sample.

Naomi.

**Comment by rjones30** [comment]
Hello Beni,

I just updated my sim-recon, and then tried running the evio-hddm plugin to
generate random events for mixing with MC to simulate background. I just
want to make sure that you are not cutting out those early hits in the
random events, the very ones we are trying to inject into the Monte Carlo
to test for the rate-dependence from early hits shadowing true hits in the
event. I see new messages showing up in the output from JANA when I run now
with the evio-hddm plugin, that I never used to see in the past.

-Richard Jones

**Comment by nsjarvis** [comment]
Hi,

It is to eliminate the repeat pulses caused by the electronics.  They occur
approx 24-32ns after an earlier large pulse.

I did something similar to produce https://logbooks.jlab.org/entry/3544091

Naomi.

**Comment by zihlmann** [comment]
Hi Sean,
in principle yes to both questions.
to 1) do you say that the push_back() function is as fast as just asking for a junk of memory. 
to 2) it is not a 3.5ns cut it is cut of 1.5*8ns cut around t=-3.5*8ns

**Comment by zihlmann** [comment]
yes 3.5

**Comment by zihlmann** [comment]
Hi Richard,
yes they are cut.
the early hits seem not to be an issue. if you do not want them to be cut
you can change the ccdb table TOF/timing_cuts which has 2 parameters
-60 and 900. representing the cut of the timing window.

**Comment by zihlmann** [comment]
Hi Naomi,
the correlation peak is aruond -3.5 
[cdc_correlationpeak.pdf](https://github.com/JeffersonLab/sim-recon/files/1802644/cdc_correlationpeak.pdf)
bins.

**Comment by sdobbs** [comment]
Richard,

We do want to reject these hits from the reconstruction, so The HDDM output
should probably be pulling CDC hits from the Calib tag. Actually we might
want to have an even lower level tag for the CDC and FDC where no quality
cuts are applied...

**Comment by rjones30** [comment]
Sean,

Yes, no QF cut. We want a level of hits that includes anything that can
saturate the fadc hit readout on that channel, and cause it to drop any
subsequent hits. How would you like to do this?

-Richard

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/make_CDCHitFactoryUpdate.log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/make_CDCHitFactoryUpdate.log)
 Build report: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/report_CDCHitFactoryUpdate.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/report_CDCHitFactoryUpdate.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/make_CDCHitFactoryUpdate.log](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/make_CDCHitFactoryUpdate.log)
 Build report: [/work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate/report_CDCHitFactoryUpdate.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^CDCHitFactoryUpdate/report_CDCHitFactoryUpdate.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^CDCHitFactoryUpdate

**Pull request merged**
