### PR TITLE
Command line options to use only fADC info in DBeamPhoton creation

### PR DESCRIPTION
**Pull request by mikestaib**
- Optional creation of DBeamPhotons with TAGH or TAGM fADC times only by command line option. 
- Command line cut on TAGM or TAGH pulse height in DBeamPhoton creation.

### CODE REVIEW

**Comment by sparksn** [comment]
I don't understand the motivation for these changes at the DBeamPhoton level, particularly for the TAGH. The calibrated hits should have TDC times available, which are more precise than the fADC times. Also, I would prefer for the pulse peak cut to be done in DTAGHHit_factory.cc instead. I was thinking about changing the current pulse integral cut to a pulse height cut anyways.

**Comment by mikestaib** [comment]
The TAGH is basically just there for completeness. In the TAGM the TDC times can be considerably worse without time walk corrections and the ADC threshold is intentionally set low allowing a lot of noise. This would mainly be for running with early calibrations.  I don't see a problem with having the possibility of changing the cut in either place, since the default behavior is to not cut at all and use the TDC times? You could imagine a case where it might be useful to see all of the hit level objects without these cuts in one plugin while simultaneously running something that uses the analysis library where these cuts are necessary for quality of the data -  the offline monitoring launches might be one of these places.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/make_TAGM_BeamPhoton.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/make_TAGM_BeamPhoton.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/report_TAGM_BeamPhoton.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/report_TAGM_BeamPhoton.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton

**Comment by sparksn** [comment]
It is better to do these things in the hit factories. Hit factories should be producing high quality products, and have sensible options available for dealing with poorly calibrated data; if not, then we need to improve them. Please let me know if you would like me to change anything for the TAGH.

**Comment by mikestaib** [comment]
Move them to wherever you think they belong, but it's a functionality that probably should exist. I still don't see the argument against it. They are flags, not default behavior.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/make_TAGM_BeamPhoton.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/make_TAGM_BeamPhoton.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/report_TAGM_BeamPhoton.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/report_TAGM_BeamPhoton.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton

**Comment by mikestaib** [comment]
Moved flags to DTAGMHit:USE_ADC and DTAGMHit:PEAK_CUT after speaking with Nathan. TAGH factory is unchanged.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/make_TAGM_BeamPhoton.log](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/make_TAGM_BeamPhoton.log)
 Build report: [/work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton/report_TAGM_BeamPhoton.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^TAGM_BeamPhoton/report_TAGM_BeamPhoton.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^TAGM_BeamPhoton

**Pull request merged**
