### PR TITLE
use tracked hits once each

### PR DESCRIPTION
**Pull request by nsjarvis**

### CODE REVIEW

**Comment by nsjarvis** [comment]
This only has a few lines different from the previous PR in branch nsj_CDC_amp_update.  I'm not sure why there are so many changes shown here, which were made in the other branch.  Maybe I forgot to make a PR for nsj_CDC_amp_update??

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/make_nsj_CDC_amp_nodupes.log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/make_nsj_CDC_amp_nodupes.log)
 Build report: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/report_nsj_CDC_amp_nodupes.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/report_nsj_CDC_amp_nodupes.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes

**Comment by faustus123** [comment]
Hi Noami,

  I’ve been confused by this before. Github shows every line different from the master so if some other changes
were committed since you last updated your branch from master, it makes it look as though you made those
changes too. At any rate, when I looked into this before, I saw that git was doing the right thing. So you should
be OK. If you want, you can always update your branch to the latest master and and re-submit. Things should
look more reassuring, but that would just be for your own peace of mind.


Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org
(757) 269-5567 W
(757) 746-6697 C

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/make_nsj_CDC_amp_nodupes.log](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/make_nsj_CDC_amp_nodupes.log)
 Build report: [/work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/report_nsj_CDC_amp_nodupes.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^nsj_CDC_amp_nodupes/report_nsj_CDC_amp_nodupes.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^nsj_CDC_amp_nodupes

**Comment by nsjarvis** [comment]
OK, I'll do that.  Thanks.

**Pull request closed without merging**
