### PR TITLE
Elton bcal led time

### PR DESCRIPTION
**Pull request by eltonssmith**
- Remove z selection cut for points in DBCALPoint_factory
- Add BCAL_LED_time plugin to monitor time offsets using LED data

### CODE REVIEW

**Comment by sdobbs** [comment]
Elton, I notice that you disabled checks on the z position in the DBCALPoint factory and suggest that they be moved to the clusterizer.  Is there a plan to make a coordinated change to add this cut to the clusterizer, or are we confident that it does not meaningfully change the high-level reconstruction results?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^elton_BCAL_LED_time/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^elton_BCAL_LED_time/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^elton_BCAL_LED_time/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^elton_BCAL_LED_time/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^elton_BCAL_LED_time/make_elton_BCAL_LED_time.log](https://halldweb.jlab.org/pull_request_test/sim-recon^elton_BCAL_LED_time/make_elton_BCAL_LED_time.log)
 Build report: [/work/halld/pull_request_test/sim-recon^elton_BCAL_LED_time/report_elton_BCAL_LED_time.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^elton_BCAL_LED_time/report_elton_BCAL_LED_time.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^elton_BCAL_LED_time

**Comment by wmcginle** [comment]
I've been using this commit today and haven't noticed any meaningful changes to the high-level reconstruction results. There are already some z-position and timing checks in the clusterizer that should reject a large fraction of these noise points.

**Comment by sdobbs** [comment]
OK, thanks Will!

**Pull request merged**
