### PR TITLE
Fcal nhits addition

### PR DESCRIPTION
**Pull request by aaust**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/make_fcal_nhits_addition.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/make_fcal_nhits_addition.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/report_fcal_nhits_addition.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/report_fcal_nhits_addition.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition

**Comment by markito3** [comment]
Resubmitting the test...

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/make_fcal_nhits_addition.log](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/make_fcal_nhits_addition.log)
 Build report: [/work/halld/pull_request_test/sim-recon^fcal_nhits_addition/report_fcal_nhits_addition.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^fcal_nhits_addition/report_fcal_nhits_addition.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition

**Comment by mashephe** [comment]
It seems the failure isn't obviously correlated with the change in the pull request?


Error [1270]: in [MySQLDataProvider::GetAssignmentShort(int, const string&, time_t, const string&)] No data was selected. Table '/CDC/hit_thresholds' for run='10000', timestampt='0' and variation='default'
JANA ERROR>>Problem loading CDC/hit_thresholds from CCDB!


Get FDC/fdc_parms parameters from CCDB...


JANA ERROR>>thread 0 has stalled on run:10000 event:1
JANA ERROR>> Thread 0 (7fcddf925700) hasn't responded in 31 seconds. (run:event=10000:1) Cancelling ...
JANA ERROR>> Caught HUP signal for thread 0x7fcddf925700 thread exiting...
JANA ERROR>>
JANA ERROR>> Last thread to lock output file mutex: 0x7fcddf925700
JANA ERROR>> Attempting to unlock mutex to avoid deadlock.
JANA ERROR>> However, the output file is likely corrupt at
JANA ERROR>> this point and the process should be restarted ...
JANA ERROR>>
JANA ERROR>>
JANA ERROR>> Automatic relaunching of threads is disabled. If you wish to
JANA ERROR>> have the program relaunch a replacement thread when a stalled
JANA ERROR>> one is killed, set the JANA:MAX_RELAUNCH_THREADS configuration
JANA ERROR>> parameter to a value greater than zero. E.g.:
JANA ERROR>>
JANA ERROR>>     jana -PJANA:MAX_RELAUNCH_THREADS=10
JANA ERROR>>
JANA ERROR>> The program will quit now.




On Jul 13, 2018, at 9:26 PM, gluex <notifications@github.com<mailto:notifications@github.com>> wrote:


Test status for this pull request: FAILURE

Failures: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/failures.txt<https://halldweb.jlab.org/pull_request_test/sim-recon%5Efcal_nhits_addition/tests-failures.txt>
Summary: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/summary.txt<https://halldweb.jlab.org/pull_request_test/sim-recon%5Efcal_nhits_addition/tests-summary.txt>
Logs: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition/tests/log<https://halldweb.jlab.org/pull_request_test/sim-recon%5Efcal_nhits_addition/tests-logs>

Build log: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition/make_fcal_nhits_addition.log<https://halldweb.jlab.org/pull_request_test/sim-recon%5Efcal_nhits_addition/make_fcal_nhits_addition.log>
Build report: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition/report_fcal_nhits_addition.txt<https://halldweb.jlab.org/pull_request_test/sim-recon%5Efcal_nhits_addition/report_fcal_nhits_addition.txt>
Location of build: /work/halld/pull_request_test/sim-recon^fcal_nhits_addition

**Comment by sdobbs** [comment]
We need to take another look at the settings for the simulated data test - they clearly aren't okay.  The tests over data are fine, so I am merging this.

**Pull request merged**
