### PR TITLE
PS energy calibration

### PR DESCRIPTION
**Pull request by abarnes12**
Plugin for the PS energy calibration for the spring 2015 run

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log)
 Build report: [/work/halld/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^PS_E_calib

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log)
 Build report: [/work/halld/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^PS_E_calib

**Comment by mikestaib** [comment]
Change your 'brun' and 'evnt' argument types to match the new JANA forms. Try to compile against Jana 0.7.4p1

**Comment by mikestaib** [comment]
More detail:

jerror_t brun(jana::JEventLoop *eventLoop, int32_t runnumber);  
jerror_t evnt(jana::JEventLoop *eventLoop, uint64_t event number);

Swap the int for int32_t and uint64_t in the .h and .cc files.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE

 Build log: [/work/halld/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log)
 Build report: [/work/halld/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^PS_E_calib

**Comment by mikestaib** [comment]
Hmm, no errors or warnings on the build report... @sdobbs ?

**Comment by mikestaib** [comment]
Won't build for me either. It's not the plugin that is causing it to fail though. Looks related to what went in yesterday.

`/w/halld-scifs1a/home/mstaib/builds/sim-recon/Linux_CentOS6-x86_64-gcc4.4.7/lib/libCDC.a(DCDCTrackHit_factory.o): In function`DCDCTrackHit_factory::evnt(jana::JEventLoop_, int)':
/work/halld2/home/mstaib/builds/sim-recon/src/libraries/CDC/DCDCTrackHit_factory.cc:172: undefined reference to `DTrackHitSelectorTHROWN::GetMCTrackHit(DCoordinateSystem const_, double, std::vector<DMCTrackHit const*, std::allocator<DMCTrackHit const*> >&, int)'
/w/halld-scifs1a/home/mstaib/builds/sim-recon/Linux_CentOS6-x86_64-gcc4.4.7/lib/libFDC.a(DFDCPseudo_factory.o): In function `DFDCPseudo_factory::makePseudo(std::vector<DFDCHit const*, std::allocator<DFDCHit const*> >&, std::vector<DFDCCathodeCluster const*, std::allocator<DFDCCathodeCluster const*> >&, std::vector<DFDCCathodeCluster const*, std::allocator<DFDCCathodeCluster const*> >&, int, std::vector<DMCTrackHit const*, std::allocator<DMCTrackHit const*> >&)':
/work/halld2/home/mstaib/builds/sim-recon/src/libraries/FDC/DFDCPseudo_factory.cc:485: undefined reference to`DTrackHitSelectorTHROWN::GetMCTrackHit(DCoordinateSystem const_, double, std::vector<DMCTrackHit const_, std::allocator<DMCTrackHit const*> >&, int)'
collect2: ld returned 1 exit status
scons: **\* [.Linux_CentOS6-x86_64-gcc4.4.7/programs/Utilities/bfield2root/bfield2root] Error 1
scons: building terminated because of errors.`

**Comment by gluex** [comment]
Build status for this pull request: SUCCESS

 Build log: [/work/halld/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/make_PS_E_calib.log)
 Build report: [/work/halld/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^PS_E_calib/report_PS_E_calib.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^PS_E_calib

**Comment by mikestaib** [comment]
GlueX bot, why do you torture me...

**Comment by mikestaib** [comment]
Branch was behind the master, compiles after merge of master into branch.

**Comment by sdobbs** [comment]
Yeah, I checked this by hand afterwards, just to be sure, and the final build was okay.  Not sure why the error messages weren't reported though.  BTW, the pull request build environment hasn't been updated to the latest JANA and CCDB versions - @markito3 is looking into this.

**Pull request merged**
