### PR TITLE
Bulletproof HDGeant SConscript against non-standard BMS_OSNAME in environment

### PR DESCRIPTION
**Pull request by faustus123**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/make_davidl_HDGeant_SConscript_debug.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/make_davidl_HDGeant_SConscript_debug.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/report_davidl_HDGeant_SConscript_debug.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/report_davidl_HDGeant_SConscript_debug.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug

**Comment by sdobbs** [comment]
Is HDGeant dead now in general, or just for these tests?

**Comment by rjones30** [comment]
For anyone watching this thread, hdgeant is alive and well. I am actively
using it today with all of the latest updates, including these pull
requests. Either we should get rid of this failing test, or we should fix
it so it starts working again.
-Richard Jones

**Comment by markito3** [comment]
Increased timeout from 180 to 360. Resubmitted test.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/make_davidl_HDGeant_SConscript_debug.log](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/make_davidl_HDGeant_SConscript_debug.log)
 Build report: [/work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/report_davidl_HDGeant_SConscript_debug.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug/report_davidl_HDGeant_SConscript_debug.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^davidl_HDGeant_SConscript_debug

**Pull request merged**
