### PR TITLE
Add a URL.

### PR DESCRIPTION
**Pull request by markito3**
This is a test change to see if the automatic build mechanism has been restored to functionality. Only the README.md is different.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/make_test_of_pull_request_build.log](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/make_test_of_pull_request_build.log)
 Build report: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/report_test_of_pull_request_build.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/report_test_of_pull_request_build.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^test_of_pull_request_build

**Comment by sdobbs** [comment]
This looks good?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/tests-logs)
 
 Build log: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/make_test_of_pull_request_build.log](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/make_test_of_pull_request_build.log)
 Build report: [/work/halld/pull_request_test/sim-recon^test_of_pull_request_build/report_test_of_pull_request_build.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^test_of_pull_request_build/report_test_of_pull_request_build.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^test_of_pull_request_build

**Comment by markito3** [comment]
Done testing. Someone can merge this one now. Looks like the auto-builds are back!

**Pull request merged**
