### PR TITLE
F250emulation fixes

### PR DESCRIPTION
**Pull request by rjones30**
This is a partial rewrite of the Df250EmulatorAlgorithm_v1 class to support multiple hits within the trigger window of a single channel, and a fix a dozen or so bugs. Support for multiple hits required a minor change to the Df250EmulatorAlgorithm base class interface, and fairly substantial changes to the JEventSource_EVIO::EmulateDf250Firmware() implementation. This code has been tested using mode 8 data from the spring 2016 run and shown to yield pulse peaks and times that are consistent with what is generated in mode 8 by the frontend modules.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS

  Summary: [/work/halld/pull_request_test/sim-recon^f250emulation_fixes/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^f250emulation_fixes/tests/summary.txt)
 Logs: [/work/halld/pull_request_test/sim-recon^f250emulation_fixes/tests/log](https://halldweb.jlab.org/pull_request_test/sim-recon^f250emulation_fixes/tests/log)

 Build log: [/work/halld/pull_request_test/sim-recon^f250emulation_fixes/make_f250emulation_fixes.log](https://halldweb.jlab.org/pull_request_test/sim-recon^f250emulation_fixes/make_f250emulation_fixes.log)
 Build report: [/work/halld/pull_request_test/sim-recon^f250emulation_fixes/report_f250emulation_fixes.txt](https://halldweb.jlab.org/pull_request_test/sim-recon^f250emulation_fixes/report_f250emulation_fixes.txt)
 Location of build: /work/halld/pull_request_test/sim-recon^f250emulation_fixes

**Comment by markito3** [comment]
@rjones30 : Looks pretty serious. I noted that you called this a partial rewrite. I there more to come? Should there be?

**Comment by rjones30** [comment]
Hello Mark,

Perhaps there needs to be. I looked into this because I needed it to
understand the mode 8 data we took with the microscope, and the emulated
TAGM_online spectra had weird artifacts that I don't see in mode 7. My goal
was to get a reasonably good fidelity emulation of mode 7 behavior. Now
with my latest updates there is complete agreement between the mode 8 pulse
information and what the emulation gives for pulse 1, which is the only one
I can check. I think it is pretty much ready for prime time, with 2 caveats:
1. mode 8 only makes a subset of the pulse objects that mode 7 makes
   (don't ask, just accept). Mode 7 makes up to 3 pulses, whereas mode 8 only
   generates pulse info for the first pulse. Mode 7 makes three objects per
   pulse (integral, time, peak) whereas mode 8 only makes time and peak
   objects.
2. the actual FPGA code for mode 7 that does the pulse analysis (time,
   integral, pedestal, etc) is separate from the code that does the same thing
   for mode 8 (again, don't ask) so the real possibility remains that
   emulating what we see in mode 8 might give subtle differences from what we
   see in mode 7 even for the first pulse.

I claim that (a) only emulating mode 7 is of interest, and (b) the only way
to check the emulation is using mode 8, but given the limitations of mode 8
in (1) above, the ability to do (emulate-7-checked-by-8) is curtailed. If
you or David can think of a better way to check it than comparison with
mode 8, I would participate. For example, someone might offer to take a
couple million TAGM windowRawData objects from mode 8 data and upload them
one by one into a f250 module and then read it out in play-back mode 7 and
record the pulse objects. If that were done, I would offer to go through
them and refine my emulation until I get 100% reproduction of the actual
mode 7 behavior. I recommend TAGM pulses because there is a large number of
multiple-pulse events in there.

-Richard Jones

**Comment by nsjarvis** [comment]
Hi,

Re the play-back suggestion at the end, the fa250 firmware people might be able to do that fairly painlessly using isim (the firmware simulator).  I've only used it live for one pulse at a time but it has a batch mode which must be intended for this.  

Naomi.

**Comment by markito3** [comment]
My understanding is that in the future, "mode 8" will contain both the summary info and the raw waveforms. That will facilitate checking of what the summary information is doing. I would hope that multiple pulses also appear in mode 8, going forward.

**Pull request merged**
